### ISSUE TITLE
[QUESTION] Failure to retrieve template?

### ISSUE THREAD

**Issue by aindriu80** [novaspirit/pi-hosted#101]
**Question**
I recently got the error 'Failure to retrieve template', what could be the cause?

**Context**
I have been following along don's tutorial on Pi Hosted and today I got the error 'Failure to retrieve template' while pointing to:

https://raw.githubusercontent.com/novaspirit/pi-hosted/master/pi-hosted_template/template/portainer-v2.json

However, I can access the following:

https://raw.githubusercontent.com/SelfhostedPro/selfhosted_templates/portainer-2.0/Template/template.json

I'm running Portainer 2.9.2 on a Raspberry Pi 4 (Ubuntu 20.04.3), I upgraded to Portainer 2.9.2.

**Comment by rmiddle** [comment]
This should be fixed at this time.  A bonehead (Me) put is a change missing a comma breaking the json file.  It has been fixed please try again.

**Comment by aindriu80** [comment]
It's working again, thanks for the fix!
