### ISSUE TITLE
[REQUEST] Add Unbound Templates to integrate with Pi-Hole

### ISSUE THREAD

**Issue by TempleZide** [novaspirit/pi-hosted#139]
Your project is awesome, and you've already incorporated Pi-hole.  However, forwarding DNS requests to Unbound to act as a validating, recursive, caching DNS resolver would be awesome. 

**Describe the solution you'd like**
Two primary options come to mind.  Setting up Unbound as a unique container, or potentially in a Stack with Pi-Hole.  Unbound can be used with other options such as Ad-Guard, so there is plenty of reason to have it separate, and using macvlan we could easily direct a standalone Pi-Hole to a standalone Unbound.

**Describe alternatives you've considered**
BIND also comes to mind, however seems to be aimed at a much large use case then Pi users.

**Additional context**
There are several Docker/Docker-Compose variations on DockerHub with unbound.  I haven't learned enough yet how to create a portainer template for it myself, however plan to continue to work on it until someone more competent then I does it. 

Thanks for any consideration on this.

**Comment by blumberg** [comment]
I've created a PR (#231) with PiHole+Unbound in a single container. I choose to go with this options as it is simpler to implement and maintain (mostly when using macvlan) and you still can use it for other applications, just need to open port 5335.
