### ISSUE TITLE
[REQUEST] feature

### ISSUE THREAD

**Issue by finnie2006** [novaspirit/pi-hosted#146]
**Is your feature request related to a problem? Please describe.**
I am missing an audio edit tool

**Describe the solution you'd like**
Add this, the readme says how to build it for arm https://github.com/linuxserver/docker-audacity

**Describe alternatives you've considered**
None
**Additional context**
None

**Comment by rmiddle** [comment]
Software in question only runs on amd64 and does not run on Arm32 or Arm64 processors.

**Comment by rmiddle** [comment]
Software in question only runs on amd64 and does not run on Arm32 or Arm64 processors.

**Comment by finnie2006** [comment]
In the readme it gives instructions to build it for arm64 like i said

**Comment by martadinata666** [comment]
the reason there is no build for arm64 was pi not strong enough to handle that kind of task, of course you can try to build it yourself as the lsio audacity readme said.
