### ISSUE TITLE
Duplicati. What "Source" folder(s) to select for effective pi-hosted backup?

### ISSUE THREAD

**Issue by iCSpotRun** [novaspirit/pi-hosted#147]
It's not clear what folders to select in the Source section of Duplicati for an effective pi-hosted/docker backup.

Thanks for your feedback in advance.

**Comment by rmiddle** [comment]
Most of the data in pi-hosted is stored under the /portainer folder if you are looking to backup the portainer data itself it defaults to /var/lib/docker/volumes/portainer_data/_data you can confirm that by going into volumes and looking at the Mount point for portainer_data

**Comment by YourMom11** [comment]
Thank you, but I can't seem to find the location in the Duplicati (Source Data) browser. It's mostly the '/AppData/Config' folder that I care about, but also can't find that in the Duplciati browser. What am I doing wrong? :(

**Comment by martadinata666** [comment]
`/source` is basically where data path you want to backup, on deploy, need to clik as `bind` and enter the path you want to backup, and vice versa to `/backup` path. As template using default to volume it will stay empty.
