### ISSUE TITLE
Chowdown - not installing arm version  ( RPI4 2gb 32bit Lite OS 

### ISSUE THREAD

**Issue by orochikun** [novaspirit/pi-hosted#149]
Quick question about the apps that are in the App template ( using https://raw.githubusercontent.com/novaspirit/pi-hosted/master/template/portainer-v2-arm32.json) 

Some of them are not installing with the proper arm version and I keep getting this error on console 
`standard_init_linux.go:228: exec user process caused: exec format error`

Is there something that Im not doing right? ( select the package and deploy is all that im doing  ) 

Rpi4 2 gb 
Raspbian 32bit Lite 
OpenMediaVault 5-6.19 ( Docker 5:20.10.10~3-0~debian-buster   and Portainer 2.9.2 installed from there )

**Comment by rmiddle** [comment]
Confirmed it is an amd64 only instance.  Checking for an ARM 32 and 64 bit version before removing.

**Comment by rmiddle** [comment]
Sorry this wasn't caught earlier.  It is an AMD64 only build and there are no builds using arm32 or arm64 so I am removing it from the list.

**Comment by orochikun** [comment]
Perfect :)

**Comment by rmiddle** [comment]
Merged in and removed from the list.  Closing the issue.
