### ISSUE TITLE
Duplicate Ports Used in 64b JSON Template.  On going project.

### ISSUE THREAD

**Issue by tuta23** [novaspirit/pi-hosted#155]
**Question**
There are several containers using duplicate ports across the 64b template.  Please see details in the attached screenshots.

**Context**
I have built out an excel review workbook to catch a few port related issues in the JSON files for 32b and 64b
![64b_Dupe_Ports_01_of_02](https://user-images.githubusercontent.com/8095757/141378268-5bb28118-2ced-4754-ab69-b51a77ecde80.JPG)

![64b_Dupe_Ports_02_of_02](https://user-images.githubusercontent.com/8095757/141378279-fb64c767-48a3-46a8-9a8d-4701cc0369fa.JPG)

**Comment by rmiddle** [comment]
Pi-Hole & Pi-Hole DoH/DoT are based on the codebase and one wont run both on the same system.
Let's Encrypt and Nginx Proxy Manager are both proxy managers and you should not be running both on the same system.
Dradis moved to 3100
Mstream moved to 3200
Plex Requests moved to 3300
Booksonic moved to 4041
Gazee Moved to 4243
NextCloudPi Moved to 4444
DashMachine moved to 5100
Port 6881 is a default port for Bittorrent so all Bittorrent clients will use that port by default.
