### ISSUE TITLE
Mealie - Incorrect tag 

### ISSUE THREAD

**Issue by orochikun** [novaspirit/pi-hosted#157]
Hey attempting to install the mealie application results in error , I  have updated the json file on my for 

From `latest`  
To `v0.4.3`

This solved the installation issue

**Comment by tuta23** [comment]
I think Mealie might have gone all in for 64bit.   

Was the 0.4.3 the latest 32b version? @orochikun

**Comment by rmiddle** [comment]
Updated to the last version to support arm32 and updated description to include it was deprecated from now on.
