### ISSUE TITLE
Snibox app does not include ARM support  portainer-v2-arm32.json

### ISSUE THREAD

**Issue by orochikun** [novaspirit/pi-hosted#161]
Attempted to use snibox from portainer-v2-arm32.json a and failed 

I managed to install updating the tool with a similiar one that does have arm support

		{
			"categories": [
				"Other",
				"Tools"
			],
			"description": "Snippet Box is a simple self-hosted app for organizing your code snippets.",
			"image": "pawelmalak/snippet-box:arm",
			"logo": "https://raw.githubusercontent.com/novaspirit/pi-hosted/master/images/snibox.png",
			"name": "Snippet-box",
			"note": "Label-oriented interface with search. Supports various programming languages, markdown, plain text.",
			"platform": "linux",
			"ports": [
				"5000:5000/tcp"
			],
			"restart_policy": "unless-stopped",
			"title": "Snippet-box",
			"type": 1,
			"volumes": [
				{
					"bind": "/portainer/Files/AppData/Config/snippet-box",
					"container": "/app/data"
				}
			]
		},

**Comment by rmiddle** [comment]
Code change merged into the main branch.
