### ISSUE TITLE
Bug - slickgear - No permission error 

### ISSUE THREAD

**Issue by orochikun** [novaspirit/pi-hosted#172]
Slickgear installation is broken ( at least it seems ) 
Since the is a permission issue as stated by the install guide ( could be that it does not apply  though ) 

https://github.com/SickGear/SickGear/wiki/Install-SickGear-%5B11%5D-RaspberryPi

`Install on RPi
Install Snap on the latest version of Raspbian...
sudo apt update
sudo apt install snapd
Reboot your system,
sudo reboot
Install and run SickGear (you must sudo)...
sudo snap install sickgear
sudo /snap/bin/sickgear (use which sickgear to find path, e.g. /snap/bin/sickgear)
SickGear will exit with a data directory write permission fail message if you do not use sudo
All done, you can access SickGear at http://localhost:8081`

Logs from sickgear 

`2021-11-13 05:48:45 ADDSHOWS^WEB_0 :: Unable to add show because can't create folder: /tv/Dragon Quest The Adventure of Dai
`

logs from doozle 

sickgear linuxserver/sickgear:latest
RUNNING
MEM 121.63 MB
LOAD 0%
0
%
today at 9:44:12 PM [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
today at 9:44:12 PM [s6-init] ensuring user provided files have correct perms...exited 0.
today at 9:44:12 PM [fix-attrs.d] applying ownership & permissions fixes...
today at 9:44:12 PM [fix-attrs.d] done.
today at 9:44:12 PM [cont-init.d] executing container initialization scripts...
today at 9:44:12 PM [cont-init.d] 01-envfile: executing... 
today at 9:44:12 PM [cont-init.d] 01-envfile: exited 0.
today at 9:44:12 PM [cont-init.d] 10-adduser: executing... 
today at 9:44:12 PM
today at 9:44:12 PM -------------------------------------
today at 9:44:12 PM           _         ()
today at 9:44:12 PM          | |  ___   _    __
today at 9:44:12 PM          | | / __| | |  /  \
today at 9:44:12 PM          | | \__ \ | | | () |
today at 9:44:12 PM          |_| |___/ |_|  \__/
today at 9:44:12 PM
today at 9:44:12 PM
today at 9:44:12 PM Brought to you by linuxserver.io
today at 9:44:12 PM -------------------------------------
today at 9:44:12 PM
today at 9:44:12 PM To support LSIO projects visit:
today at 9:44:12 PM https://www.linuxserver.io/donate/
today at 9:44:12 PM -------------------------------------
today at 9:44:12 PM GID/UID
today at 9:44:12 PM -------------------------------------
today at 9:44:12 PM
today at 9:44:12 PM User uid:    1000
today at 9:44:12 PM User gid:    44
today at 9:44:12 PM -------------------------------------
today at 9:44:12 PM
today at 9:44:12 PM [cont-init.d] 10-adduser: exited 0.
today at 9:44:12 PM [cont-init.d] 30-config: executing... 
today at 9:47:00 PM [cont-init.d] 30-config: exited 0.
today at 9:47:00 PM [cont-init.d] 90-custom-folders: executing... 
today at 9:47:00 PM [cont-init.d] 90-custom-folders: exited 0.
today at 9:47:00 PM [cont-init.d] 99-custom-files: executing... 
today at 9:47:00 PM [custom-init] no custom files found exiting...
today at 9:47:00 PM [cont-init.d] 99-custom-files: exited 0.
today at 9:47:00 PM [cont-init.d] done.
today at 9:47:00 PM [services.d] starting services
today at 9:47:00 PM [services.d] done.
today at 9:47:25 PM /app/sickgear/lib/tzlocal/unix.py:158: UserWarning: Can not find any timezone configuration, defaulting to UTC.
today at 9:47:25 PM   warnings.warn('Can not find any timezone configuration, defaulting to UTC.')
today at 9:47:25 PM 05:47:25 INFO TORNADO :: Starting SickGear on http://0.0.0.0:8081/
today at 9:47:25 PM 05:47:25 INFO MAIN :: Upgrading
today at 9:47:28 PM 05:47:28 INFO MAIN :: Removed orphaned data from allowlist
today at 9:47:28 PM 05:47:28 INFO MAIN :: Removed orphaned data from blocklist
today at 9:47:28 PM 05:47:28 INFO MAIN :: Adding TV info support to history table
today at 9:47:29 PM 05:47:29 INFO MAIN :: Adding TV info support to scene_exceptions table
today at 9:47:29 PM 05:47:29 INFO MAIN :: Removed orphaned data from scene_exceptions
today at 9:47:29 PM 05:47:29 INFO MAIN :: Adding TV info support to scene_numbering
today at 9:47:29 PM 05:47:29 INFO MAIN :: Adding TV info support to imdb_info
today at 9:47:29 PM 05:47:29 INFO MAIN :: Changing/Re-Creating Indexes
today at 9:47:31 PM 05:47:31 INFO MAIN :: Adding rls_global_exclude_ignore, rls_global_exclude_require to tv_shows
today at 9:47:31 PM 05:47:31 INFO MAIN :: Adding new data columns to tv_shows
today at 9:47:31 PM 05:47:31 INFO MAIN :: Adding new data columns to tv_episodes
today at 9:47:31 PM 05:47:31 INFO MAIN :: Adding new data columns to imdb_info
today at 9:47:32 PM 05:47:32 INFO MAIN :: Adding Character and Persons tables
today at 9:47:33 PM 05:47:33 INFO MAIN :: Finished
today at 9:47:33 PM 05:47:33 INFO MAIN :: Checking database structure...
today at 9:47:33 PM 05:47:33 INFO MAIN :: Initial Schema
today at 9:47:33 PM 05:47:33 INFO MAIN :: Database upgrade required: Initial Schema
today at 9:47:33 PM 05:47:33 INFO MAIN :: Consolidate Providers
today at 9:47:33 PM 05:47:33 INFO MAIN :: Database upgrade required: Consolidate Providers
today at 9:47:33 PM 05:47:33 INFO MAIN :: Add Backlog Parts
today at 9:47:33 PM 05:47:33 INFO MAIN :: Database upgrade required: Add Backlog Parts
today at 9:47:33 PM 05:47:33 INFO MAIN :: Add Provider Failure Handling
today at 9:47:33 PM 05:47:33 INFO MAIN :: Database upgrade required: Add Provider Failure Handling
today at 9:47:33 PM 05:47:33 INFO MAIN :: Add Indexer To Tables
today at 9:47:33 PM 05:47:33 INFO MAIN :: Database upgrade required: Add Indexer To Tables
today at 9:47:33 PM 05:47:33 INFO MAIN :: Add Generic Failure Handling
today at 9:47:33 PM 05:47:33 INFO MAIN :: Database upgrade required: Add Generic Failure Handling
today at 9:47:33 PM 05:47:33 INFO MAIN :: Add Save Queues
today at 9:47:33 PM 05:47:33 INFO MAIN :: Database upgrade required: Add Save Queues
today at 9:47:33 PM 05:47:33 INFO MAIN :: Finished
today at 9:47:33 PM 05:47:33 INFO MAIN :: Checking database structure...
today at 9:47:33 PM 05:47:33 INFO MAIN :: Initial Schema
today at 9:47:33 PM 05:47:33 INFO MAIN :: Database upgrade required: Initial Schema
today at 9:47:33 PM 05:47:33 INFO MAIN :: Size And Provider
today at 9:47:33 PM 05:47:33 INFO MAIN :: Database upgrade required: Size And Provider
today at 9:47:33 PM 05:47:33 INFO MAIN :: History
today at 9:47:33 PM 05:47:33 INFO MAIN :: Database upgrade required: History
today at 9:47:33 PM 05:47:33 INFO MAIN :: History Status
today at 9:47:33 PM 05:47:33 INFO MAIN :: Database upgrade required: History Status
today at 9:47:33 PM 05:47:33 INFO MAIN :: Add Indexer To Tables
today at 9:47:33 PM 05:47:33 INFO MAIN :: Database upgrade required: Add Indexer To Tables
today at 9:47:34 PM 05:47:34 INFO MAIN :: Finished
today at 9:47:34 PM 05:47:34 INFO MAIN :: Updating TV Episode table with index idx_tv_ep_ids
today at 9:47:34 PM 05:47:34 INFO MAIN :: No orphan episodes, check passed
today at 9:47:34 PM 05:47:34 INFO MAIN :: No UNAIRED episodes, check passed
today at 9:47:35 PM /app/sickgear/lib/dateutil/zoneinfo/__init__.py:32: UserWarning: Falling back to included zoneinfo file
today at 9:47:35 PM   warnings.warn('Falling back to included zoneinfo file')
today at 9:47:35 PM 05:47:35 INFO MAIN :: Updating timezone info with new one: zoneinfo-2021e.tar.gz
today at 9:47:37 PM 05:47:37 INFO MAIN :: Loading initial show list
today at 9:47:37 PM 05:47:37 INFO MAPPINGSUPDATER :: Start loading TV info mappings...
today at 9:47:37 PM 05:47:37 INFO MAPPINGSUPDATER :: TV info mappings loaded
today at 9:47:37 PM 05:47:37 INFO XEMUPDATER :: Fetching show ids with xem scene mappings for origin TheTVDB
today at 9:47:37 PM 05:47:37 INFO UPGRADE-HISTORY-ACTION :: Updating history items with status Snatched Proper in a background process...
today at 9:47:38 PM 05:47:38 INFO XEMUPDATER :: Finished fetching show ids with 1216 xem scene mappings for origin TheTVDB
today at 9:48:45 PM 05:48:45 ERROR ADDSHOWS^WEB_0 :: Unable to add show because can't create folder: /tv/Dragon Quest The Adventure of Dai

**Comment by rmiddle** [comment]
The package is inside the container so you don't need to worry about the snap stuff.  Let me review the install and see what is going on.

**Comment by rmiddle** [comment]
Based on the error make and the containers default settings.  Make sure the /portainer/TV is owned but user 1000 and group 1000.  

IF you are not sure how to do that than run:

sudo chown -R 1000.1000 /portainer/TV

Also wouldn't hurt to also down the download folder as well.

sudo chown -R 1000.1000 /portainer/Downloads

If this doesn't fix you issue let me know.

**Comment by orochikun** [comment]
Will try later today and report back !

**Comment by orochikun** [comment]
Problem solved with those commands :)
