### ISSUE TITLE
whoogle-search Fatal Python error

### ISSUE THREAD

**Issue by Aman733t** [novaspirit/pi-hosted#175]
Hello,

Getting error after installing whoogle using Portainer

whoogle-search Fatal Python error: pyinit_main: can't initialize time Python runtime state: core initialized PermissionError: [Errno 1] Operation not permitted

**Comment by martadinata666** [comment]
as far as i can tell this because old version libseccomp2, check the libseccomp2 upgrade notes.

**Comment by code123-creator** [comment]
Did you try updating python or installing python3?

**Comment by Macleykun** [comment]
I think this one can be closed. Just tested whoogle-search and it's working as expected.
