### ISSUE TITLE
Failure json: cannot unmarshal object into Go value of type []portainer.Template

### ISSUE THREAD

**Issue by frohlichcortezh** [novaspirit/pi-hosted#2]
I'm running into this error after using the raw json URL.
Running Portainer 1.24.2 with ```portainer:linux-arm``` on RPi 4 8 GB (Raspbian GNU/Linux 10 (buster)) Raspberry Pi OS with desktop and recommended software

I've tried updating portainer to ```portainer-ce:linux-arm``` and ```portainer-ce:linux-arm-2.9.0```

I'd appreciate any help.
And thanks for the videos, great job !

**Comment by novaspirit** [comment]
give it a try now, i just modified one of things i think might be causing the issue

**Comment by frohlichcortezh** [comment]
yes, it's fixed. 
thanks!
