### ISSUE TITLE
Mylar -- 32b image has been deprecated

### ISSUE THREAD

**Issue by tuta23** [novaspirit/pi-hosted#218]
When trying to spin up the Mylar container on the 32b side -- the logs revealed that the image is being deprecated and to use this branch instead:

linuxserver/mylar3

**Comment by rmiddle** [comment]
Mylar replaced with Mylar3.  Please confirm it is working well for you.

**Comment by tuta23** [comment]
Container does spin up -- there is a fair amount of setup required, but I was able to get things connected and successfully tested a file download.

There is one main section "StoryArcs" that breaks the GUI with the below message.  I don't think this is container setup related but possibly related to the linuxserver image itself?

Error !
TypeError: expected str, bytes or os.PathLike object, not NoneType
<legend>Global StoryArc Options</legend> <div class="row checkbox left clearfix"> <% storyarcdest = os.path.join(mylar.CONFIG.DESTINATION_DIR, 'StoryArcs') %> <input type="checkbox" style="vertical-align: middle; margin: 3px; margin-top: -1px;" onclick="getOption(this)" name="storyarcdir" id="storyarcdir" value="1" ${checked(mylar.CONFIG.STORYARCDIR)} /><label>Arcs in StoryArc Directory </br><small>(${storyarcdest})</small></label> </div> <div id="arc_options"> <div class="row">
