### ISSUE TITLE
[BUG] Unable to retrieve templates?

### ISSUE THREAD

**Issue by aindriu80** [novaspirit/pi-hosted#220]
**Question**
Getting Unable to retrieve templates when using https://github.com/novaspirit/pi-hosted/blob/master/template/portainer-v2-arm64.json

**Context**
When using the 64 bit version of the templates I am getting the following error - 

Unable to retrieve templates

![2021-11-28_16-28](https://user-images.githubusercontent.com/8885837/143776982-f58f0d42-802c-4989-89f8-bc8ceb99f351.png)

Template:
https://github.com/novaspirit/pi-hosted/blob/master/template/portainer-v2-arm64.json

It seems as though the json file is not surrounded by [ ] but I'm not sure if that is the cause of the error.

**Comment by aindriu80** [comment]
![2021-11-28_16-37](https://user-images.githubusercontent.com/8885837/143777298-87d7fc73-ba67-48b5-baca-312c281bd896.png)
Here is a screenshot from the dev tools, I'm getting the same error with the original template so it might be something wrong my end, any ideas?

**Comment by aindriu80** [comment]
It appears to be a network problem ><

**Comment by delight** [comment]
https://raw.githubusercontent.com/novhttps://raw.githubusercontent.com/novaspirit/pi-hosted/master/template/portainer-v2-arm64.jsonaspirit/pi-hosted/master/template/portainer-v2-arm64.json

you need to point to the raw file not the github page displaying the file content

no bug here - please close

**Comment by rmiddle** [comment]
Likely related to the problems github had.  Closing.
