### ISSUE TITLE
Docker monitoring not showing up in portainer App templates

### ISSUE THREAD

**Issue by JRTax** [novaspirit/pi-hosted#246]
I've followed the tutorial for installing the rpi docker monitor using the [docs ](https://github.com/novaspirit/pi-hosted/blob/master/docs/rpi_docker_monitor.md), but the "Raspberry Pi Docker Monitor" doesn't show up in the App templates tab. There aren't any errors showing up see the output below.
![RPIMON](https://user-images.githubusercontent.com/14052806/146250801-e5f76415-603f-4e2e-8f94-458046956a18.png)

I'm using portainer.io version 2.11.0
Raspbian GNU/ Linux 11 (bullseye)

What could be causing this issue?

**Comment by JRTax** [comment]
I've fixed the issue, by switching the template definition file to https://raw.githubusercontent.com/novaspirit/pi-hosted/master/template/portainer-v2-arm32.json instead of the one listed in the video.

**Comment by rmiddle** [comment]
Stacks don't show up when docker is in swarm mode.  That is why switching to type 2 fixed the issue.  No changes needed in template, as we don't officially support swarm mode.
