### ISSUE TITLE
[QUESTION / BUG] Docker Monitoring station using Grafana

### ISSUE THREAD

**Issue by MrAgentSmith** [novaspirit/pi-hosted#248]
I set up the Docker Monitoring, all fine as per your video, and it all worked great, (other than a couple of minnor statistics which I mentioned below).  A day later I restarted my Pi and suddently all the statistics in Grafana showed N/A.  After looking and the logs and doing some investigating it appears that the 4 containers (Cadvisor, Prometheus, Grafana, Node-Exporter) all have a DHCP assigned IP.  However, Grafana is expecting to get data from a certain IP (in my case xxx.xxx.xxx.2) the Prometheus container.  Therefore if when all the containers start up and Prometheus isn't on .2, Grafana fails.

I'm very new to all of this, and not sure how you've got them containers to be on their own seperate network.  Thus I'm not sure how to fix their internal IP addresses.  Hence, I'm not sure whether this is a bug in the setup or some other issue.

The following are bugs, relating to getting some of the statistics working, which although not connected, thought I would mention.

I found that the "Used Memory per Coantiner" table and graph always showed 0 for all containers.  As per the information on https://issueexplorer.com/issue/stefanprodan/dockprom/228 I set cgroup_memory=1 cgroup_enable=memory in \boot\cmdline.txt and the used memory is now working.  Note, I still get 0 for Limit memory and RSS Memory Usage per Container, but I suspect the former is due to me now setting a limit and I don't know about the later.

The number of containers also shows N/A from the very start.  I had to change the Metric to count(rate(container_last_seen{id=~"/system.slice/docker.*"}[5m]))-2 to give the correct value.  The minus two, is due to the count including docker.socket and docket.service which in my opinion weren't containers.

Thanks for all the great work, it is much appreciated.

**Comment by martadinata666** [comment]
https://github.com/novaspirit/pi-hosted/blob/master/docs/rpi_docker_monitor.md

**Comment by MrAgentSmith** [comment]
Thank you very much, I've got it all up and running.
