### ISSUE TITLE
[Redmine] feature

### ISSUE THREAD

**Issue by romeo81** [novaspirit/pi-hosted#262]
**Is your feature request related to a problem? Please describe.**
another great way to document your own personal wikis and has other add in as well in the https://www.redmine.org

Ive pulled it from the base link in Portainer:
linking for reference 
https://raw.githubusercontent.com/portainer/templates/master/templates-2.0.json

**Describe the solution you'd like**

**Additional context**
```
{
			"type":1,
			"title":"Redmine",
			"description":"Open-source project management tool",
			"note":"Default user and password are admin/admin",
			"categories":[
				"project-management"
			],
			"platform":"linux",
			"logo":"https://portainer-io-assets.sfo2.digitaloceanspaces.com/logos/redmine.png",
			"image":"redmine:latest",
			"ports":[
				"3000/tcp"
			],
			"volumes":[
				{
					"container":"/usr/src/redmine/files"
				}
			]
		}
```

**Comment by rmiddle** [comment]
Working on adding it to the repo.  Will close the request when testing is complete.

**Comment by rmiddle** [comment]
Added to template.  Closing the request.
