### ISSUE TITLE
qbittorrent login credentials

### ISSUE THREAD

**Issue by djayor** [novaspirit/pi-hosted#264]
Hi, after the deploy of "qbittorrent" I cannot pass the authentication screen using the credentials:
Username: admin
Password: adminadmin

But also didn't give me any error, unless I try another random combination.
I tested with Safari, Chrome and Firefox, same result.

**Comment by rmiddle** [comment]
The default login and password are admin / adminadmin .

Reset instructions at 
https://github.com/qbittorrent/qBittorrent/wiki/Web-UI-password-locked-on-qBittorrent-NO-X-%28qbittorrent-nox%29

Thanks
Robert Middleswarth

**Comment by djayor** [comment]
I already saw what I did wrong on the log file:
"Your DockerHost is running an outdated version of libseccomp"

After I run:
$ wget -qO- https://git.io/JPXdj | bash

It's already working with the default combination of username/password.
