### ISSUE TITLE
[REQUEST] replace deprecated rutorrent image

### ISSUE THREAD

**Issue by djayor** [novaspirit/pi-hosted#265]
Hi! The used image for rutorrent: "[linuxserver/rutorrent:latest](https://hub.docker.com/r/linuxserver/rutorrent)" is deprecated since version 25.03.21 (or 25.03.22 like the version history on docker hub).

Can be replaced by [crazymax/rtorrent-rutorrent](https://hub.docker.com/r/crazymax/rtorrent-rutorrent).
Thanks!

**Comment by rmiddle** [comment]
There is no documentation attached to that docker instance.  Could you point me at their document?

**Comment by djayor** [comment]
Sure, documentation link is on the overview on docker hub:
https://github.com/crazy-max/docker-rtorrent-rutorrent

**Comment by rmiddle** [comment]
The template has been updated, including adding in several new env variables.
