### ISSUE TITLE
[REQUEST] feature Raspberry Pi Docker Monitor all file systems

### ISSUE THREAD

**Issue by ramsrq** [novaspirit/pi-hosted#270]
Is it possible to include all file systems in then panel "Used disk space"? 

I recently install the stack "raspberrypi-docker-monitor" and saw that the mention panel only include data related to root fs (/).

I wish see other fs in then panel, such as root, boot and some externals disks

**Comment by rmiddle** [comment]
It actually monitors the file systems that holds /etc/resolv.conf .  There doesn't seem to be a system to monitor all file systems, you can edit the panel and add additional file systems into it, but there doesn't seem to be a way to monitor all file systems by default.
