### ISSUE TITLE
Sshwifty app template doesn't work. Can't connect via HTTPS.

### ISSUE THREAD

**Issue by Fretzy** [novaspirit/pi-hosted#277]
I saw the Sshwifty app in the templates file and tried to install that through Portainer rather than installing shellinabox with apt. I can access Sshwifty via http://localhost:8182, but it refuses to connect via https://localhost:8182. 

Sshwifty won't allow connections without HTTPS. I tried generating credential files and setting them as ENV variables as described in https://hub.docker.com/r/niruix/sshwifty, but not only did that not work, but it also makes it so that Sshwifty can no longer be accessed via HTTP, either. A delete/reinstall cycle restores HTTP functionality, of course.

**Comment by blumberg** [comment]
You do need to have `https` connection for it to work. The easiest way is to setup a reverse proxy (**Nginx** or **Traefik**) in front to deal with certification.

The other way is to create another volume so you can pass the cert file to Sshwifty. Pasting the cert into portainer ENV didn´t worked for me.

Take a look at this issue https://github.com/nirui/sshwifty/issues/49 as he describes a few ways to get it done.

I'll try to write some tutorial later to help with this app

**Comment by rmiddle** [comment]
Need to get this documentated
