### ISSUE TITLE
Drupal doesn't connect to database.

### ISSUE THREAD

**Issue by bsorescu** [novaspirit/pi-hosted#283]
Deployment goes OK, but after that, I'm unable to connect to the data base during the install process. I've seen in the composer file that no port is exposed for mariadb container, but phpMyAdmin is pointing to port 3306 for the database. I've tried to add the port to the configuration for the database with no luck. In the advanced settings for the database connection I can see localhost and port 3306 selected. I get the folowing:

**SQLSTATE[HY000] [2002] No such file or directory.** with 'localhost' selected in the advanced settings
and 
**SQLSTATE[HY000] [2002] Connection refused.** with 127.0.0.1 selected

- both settings tested with or without port 3306 

Installation is on a raspberry pi4 and I've used the install_drupal.sh before deploying the stack.

**Comment by martadinata666** [comment]
use the container name mariadb instead of localhost

**Comment by bsorescu** [comment]
Unfortunately i get this error now: 

**SQLSTATE[HY000] [1045] Access denied for user 'drupal'@'drupal.drupal_drupal_network' (using password: YES).**

**Comment by bsorescu** [comment]
that worked, thak you!
