### ISSUE TITLE
[REQUEST] tinkerboard support

### ISSUE THREAD

**Issue by code123-creator** [novaspirit/pi-hosted#288]
installation script doesnt work on my tinker board s it gives these errors:
_curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it_

_gpg: no valid OpenPGP data found._

i think the way to fix curl problem is by adding -k before the url to not verify ssl

**Comment by martadinata666** [comment]
What OS is it? is `ca-certificates` package installed?
Try run `dpkg-query -s ca-certificates`

**Comment by code123-creator** [comment]
it says that its installed

**Comment by Griffen8280** [comment]
Is this request complete?  According to tinker
Tinker Board | Tinker Board S | Tinker Board R2.0 | Tinker Board S R2.0
   ARMv7-A   |       ARMv7-A    |         ARMv7-A       |         ARMv7-A

Tinker Edge T | Tinker Edge R | Tinker Board 2 | Tinker board 2S
     ARMv8       |       ARMv8      |        ARMv8      |       ARMv8

These architectures should be compatible with the current 32/64 bit application lists.

**Comment by Macleykun** [comment]
Are you still having this issue @code123-creator ?

**Comment by rmiddle** [comment]
Tinker Board seems to have their own process for installing docker.  However, once you install docker the install_portainer should work fine.  Close
