### ISSUE TITLE
[REQUEST] Prowlarr

### ISSUE THREAD

**Issue by NightHawkATL** [novaspirit/pi-hosted#290]
Logo URL:
 - https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/prowlarr-banner.png

Description:
- Prowlarr is an indexer manager/proxy built on the popular arr .net/reactjs base stack to integrate with your various PVR apps. Prowlarr supports both Torrent Trackers and Usenet Indexers. It integrates seamlessly with Sonarr, Radarr, Lidarr, and Readarr offering complete management of your indexers with no per app Indexer setup required (we do it all).

ARM64 & ARMHF supported and tested. Project is still under development, so you have to grab the develop or nightly (nightly worked for me but not develop) build to get the image to download.

Linuxserver.io link: https://github.com/linuxserver/docker-prowlarr

Compose:
 ---
version: "2.1"
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:nightly
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/new_york
    volumes:
      - /portainer/Files/AppData/Config/Prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

**Comment by Griffen8280** [comment]
If everything is functioning properly for you feel free to close this request.
