### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by KostGames22** [novaspirit/pi-hosted#292]
when i want to install something from portainer it says: No such image

**Comment by Macleykun** [comment]
Do you install it from the template page found here: :9000/#!/2/docker/templates ?
Adding screenshots would also help, which image, is it with all or only some?

**Comment by Macleykun** [comment]
@KostGames22 do you still need help?

**Comment by rmiddle** [comment]
No Reply in months.  Closing.
