### ISSUE TITLE
[QUESTION] Raspberry Pi Dockers Monitor error 

### ISSUE THREAD

**Issue by ramsrq** [novaspirit/pi-hosted#295]
**Question**
I got an error in Grafana Raspberry Pi Dockers Monitor with charts "CPU Busy" and "Disk IO"

**Context**
I just install the stack RaspberryPi-Docker-Monitor in a RPi 4 with:
pi@raspberrypi:~ $ cat /etc/os-release 
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

After follow all steps documented on https://github.com/pi-hosted/pi-hosted/blob/master/docs/rpi_docker_monitor.md in Grafana dashboard a got an error in "CPU Busy" and "Disk IO" charts: 

**bad_data: 1:38: parse error: not a valid duration string: "2.147483647s"**

![image](https://user-images.githubusercontent.com/57735189/153515091-571c7b1a-77a6-4fdc-a918-eee496e88ef8.png)

Is it possible to correct it?

**Comment by davide-v15** [comment]
Installed now and I have the same error

**Comment by Bluesguy1984** [comment]
> Installed now and I have the same error.
> 
> Edit: The problem is in the string $__rate_interval. I temporaly set the range to calculate rate() fonction as $__interval instead using $__rate_interval but I cin this way an't optimize the monitor of CPU and I/O Disk. You can read this docs to have a better idea. (https://grafana.com/blog/2020/09/28/new-in-grafana-7.2-__rate_interval-for-prometheus-rate-queries-that-just-work/)

I am getting the same error.  Where did you make the change?  What file?

**Comment by davide-v15** [comment]
> > Installed now and I have the same error.
> > Edit: The problem is in the string $__rate_interval. I temporaly set the range to calculate rate() fonction as $__interval instead using $__rate_interval but I cin this way an't optimize the monitor of CPU and I/O Disk. You can read this docs to have a better idea. (https://grafana.com/blog/2020/09/28/new-in-grafana-7.2-__rate_interval-for-prometheus-rate-queries-that-just-work/)
> 
> I am getting the same error. Where did you make the change? What file?

You need to modify it in the query. 
Clink on the box title (like CPU busy), go in to the edit menu and you can find the query that the monitor use to get the data from database.

**Comment by ramsrq** [comment]
Thanks @davide-v15 I'll try this workaround

**Comment by Colcobau** [comment]
> > > Installed now and I have the same error.
> > > Edit: The problem is in the string $__rate_interval. I temporaly set the range to calculate rate() fonction as $__interval instead using $__rate_interval but I cin this way an't optimize the monitor of CPU and I/O Disk. You can read this docs to have a better idea. (https://grafana.com/blog/2020/09/28/new-in-grafana-7.2-__rate_interval-for-prometheus-rate-queries-that-just-work/)
> > 
> > 
> > I am getting the same error. Where did you make the change? What file?
> 
> You need to modify it in the query. Clink on the box title (like CPU busy), go in to the edit menu and you can find the query that the monitor use to get the data from database.

Thank you! Was having the exact same issue, modified the query and works like a charm. Star!

**Comment by Macleykun** [comment]
I'm also having some issues, while it's not the cpu it's the memory usage per container views
![image](https://user-images.githubusercontent.com/26381427/158012779-9975ed74-3887-497a-bed3-d186e6ed5414.png)
Anyone has this problem aswell? It also happens with th IO of the containers but not with the cpu usage per container weirdly enough.

**Comment by Macleykun** [comment]
> Thanks @davide-v15 I'll try this workaround Edit: I change the variable from $__rate_interval to $__interval and work for me. ![image](https://user-images.githubusercontent.com/57735189/156436176-a9b935bf-32e6-45f2-9320-9b6f2ea2dcf9.png)

ya can close this issue :)

**Comment by Macleykun** [comment]
This isssue can be closed @ramsrq
