### ISSUE TITLE
[Issue] ruTorrent (Failure: No such image)

### ISSUE THREAD

**Issue by djayor** [novaspirit/pi-hosted#296]
Hi, I was trying to deploy the ruTorrent template, but I get several errors:
- Ports are not defined:
![Screenshot 2022-02-09 at 19 14 36](https://user-images.githubusercontent.com/1130405/153721708-e6d4bb1a-2772-4671-a514-48b79a5428f8.png)

- Even after adding manually the ports, I get this error:
![Screenshot 2022-02-09 at 19 13 45](https://user-images.githubusercontent.com/1130405/153721728-523c8083-4dc2-4e08-a5a1-f27d8bf12ca0.png)

Maybe the path to docker hub image it's wrong.
Thanks!

**Comment by Macleykun** [comment]
You're correct! linuxserver/ has to be removed, can you test if it works with using this image path instead?
crazymax/rtorrent-rutorrent:latest
If that works, i'll make a pull to fix that :)

**Comment by djayor** [comment]
But how I can deploy if the port mapping it's still not fully filled correctly? I get immediately a fail on port mapping.
I think the port mapping should be:
5324 -> 80 TCP
51413 -> 51413 TCP
6881 -> 6881 - UDP

You can do a pull because the template it's not deploying at all anyway.
Thanks!

**Comment by rmiddle** [comment]
Template docker image link updated in an PR that should fix this issue.  Closing.
