### ISSUE TITLE
[QUESTION] Nginx Proxy Manager - Bad Gateway 

### ISSUE THREAD

**Issue by FilipLac** [novaspirit/pi-hosted#297]
**Question**
Bad Gateway on login screen after setting up Nginx Proxy Manager using template. What can I do ?

**Context**
I was following everything that was mentioned in video and after deploying container I am unable to log in (getting bad gateway error).
When I looked up in portainer log for NPM it showed this:
![image](https://user-images.githubusercontent.com/93822443/154104465-d6f785d4-d199-41f5-83a7-5fb1165a2665.png)

How can I fix it ?

**Comment by SomeDood00** [comment]
I had a similar problem
https://nginxproxymanager.com/setup/#running-on-raspberry-pi-arm-devices

Please note that the jc21/mariadb-aria:latest image might have some problems on some ARM devices, if you want a separate database container, use the yobasystems/alpine-mariadb:latest image.

**Comment by FilipLac** [comment]
Ok, so Mariadb is causing this ? So if I switch to alpine it should work ?

**Comment by martadinata666** [comment]
If the error about `transaction lock` thing then maybe change db will help.

**Comment by FilipLac** [comment]
No, I am getting Bad Gateway on login and in logs there is some error in ./run line 19 (i think) which is saying something about illegal operation on some production.json file or so

**Comment by FilipLac** [comment]
Ok, I will look it up. Thanks

**Comment by FilipLac** [comment]
Ok, I fixed it :D Thanks for any suggestions
