### ISSUE TITLE
[REQUEST] grafana

### ISSUE THREAD

**Issue by code123-creator** [novaspirit/pi-hosted#307]
add grafana its a cool monitoring thing that can monitor whatever u want

**Comment by Macleykun** [comment]
Technically there's already Raspberry Pi Docker Monitor which is based on grafana. You can add your own dashboards ontop of that!

**Comment by code123-creator** [comment]
ok thanks.. but there is one problem and its that when i deploy the stack, only three of them is created, and the monitoring-grafana wont start, it just stays in [Created].. it also says limited access so probably gonna need help with that
![Screenshot (112)](https://user-images.githubusercontent.com/65112695/158632144-45cafa28-49e0-498b-82b4-1a2577ac0ae0.png)

**Comment by code123-creator** [comment]
the log is empty.. it never even started even when i try to, and the stack appears to have limited control for some reason tho im logged in as admin

**Comment by Macleykun** [comment]
> the log is empty.. it never even started even when i try to, and the stack appears to have limited control for some reason tho im logged in as admin

mmm strange, i follow the tutorial and for me, it all came up (tho i didn't do the cmd part right and didn't get all the information).

Have you tried removing the entire stack with the volumes and refollowing the tutorial (but maybe not as root, this might be the reason why the log is empty, as the container may not able to write to it?)

**Comment by rivasabb** [comment]
> the log is empty.. it never even started even when i try to, and the stack appears to have limited control for some reason tho im logged in as admin

I noticed that the permissions for this are crucial. If you are sharing the stock via SAMBA the container does not start.

**Comment by rmiddle** [comment]
Added Grafana itself to the list.  Closing the request.
