### ISSUE TITLE
[QUESTION] Why not change from zcube/cadvisor:v0.37.5 to zcube/cadvisor:latest ?

### ISSUE THREAD

**Issue by Macleykun** [novaspirit/pi-hosted#310]
From here i noticed that a specific version is used
https://github.com/novaspirit/pi-hosted/blob/55c9f96d1821e8cb6ee77164cece4b6f70a05b5e/stack/raspberrypi-monitoring.yml#L10

I tested the latest but having no issues, is there a reason that this specific version was used instead of latest?

**Comment by rmiddle** [comment]
PR that made this change was commited.  Closing.
