### ISSUE TITLE
[QUESTION] Pi-Hole : three options?

### ISSUE THREAD

**Issue by Bluesguy1984** [novaspirit/pi-hosted#316]
**Question**
There are three Pi-Hole App templates, what are the Pros/Cons for each one?

**Context**
I am thinking about installing Pi-Hole in my Pi Server as a Container.  I already have a dedicated RPi-4 as a Pi-Hole device.

**Comment by blumberg** [comment]
I don't have much knowledge for Pros and Cons, so a PR to include that is always appreciate.

Basically you have:

- **Pi-Hole:** Official Pi-Hole docker with only Pi-Hole software installed. This should be the default for most people
- **Pi-Hole-Unbound:** This one includes [Unbound](https://nlnetlabs.nl/projects/unbound/about/) DNS resolver, so you don't need to rely on external DNS. It improves in privacy and sometimes speed but adds some overhead. _(That's the option I personally use)_
- **Pi-Hole DoH/DoT:** This one includes a protocol to send your DNS request over HTTPs ([DoH](https://en.wikipedia.org/wiki/DNS_over_HTTPS)) or over TLS ([DoT](https://en.wikipedia.org/wiki/DNS_over_TLS)). I don't have much knowledge on this one, but it also improves privacy.

So it's up to you what you are looking for, if it's just to block Trackers and Ads, then the Official one should be enough. If you're looking for privacy, then you need to investigate yourself which one of the other 2 options is better for your scenario.

If this have answered your question, please consider closing this Issue.

**Comment by Bluesguy1984** [comment]
Thank you for the information.
