### ISSUE TITLE
Nginx Proxy Manager Bad Gateway

### ISSUE THREAD

**Issue by roely15mol** [novaspirit/pi-hosted#318]
I deployed the stack after I runned the script on the terminal and everything seems to work fine. But when I want to login I get the following error: Bad Gateway. 
![image](https://user-images.githubusercontent.com/58187423/159547982-335e8e59-92a2-4125-9960-365efe328ee9.png)

**Comment by rmiddle** [comment]
Bad Gateway almost always means that the DB server didn't load correctly.  I would remove the stack.  Delete the folder.  Rerun the script and reinstall from scratch the template.

**Comment by kkuubb** [comment]
I also can't get past it, reinstalling didn't help

**Comment by roely15mol** [comment]
Fixed it with an other database. But tried it with the this database on another pi and it worked. Idk what the problem is.
