### ISSUE TITLE
[REQUEST] feature add AdGuard home?

### ISSUE THREAD

**Issue by Macleykun** [novaspirit/pi-hosted#325]
I’ve seen this template: https://raw.githubusercontent.com/technorabilia/portainer-templates/main/lsio/templates/templates-2.0.json
And though, why not add adguard from that?
Source https://www.reddit.com/r/portainer/comments/mlzp8z/140_portainer_app_templates_for_linuxserverio/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

**Comment by rmiddle** [comment]
1) Have you confirmed the template has arm32 and arm64 support?  
2) I will generally accept anything that someone generates a PR.

**Comment by technorabilia** [comment]
It should if I read [this](https://docs.linuxserver.io/images/docker-adguardhome-sync).

**Comment by Macleykun** [comment]
heya

It seems i added the wrong container xD, wanted to get adguard-home haha

docker run --name adguardhome\
    --restart unless-stopped\
    -v /my/own/workdir:/opt/adguardhome/work\
    -v /my/own/confdir:/opt/adguardhome/conf\
    -p 53:53/tcp -p 53:53/udp\
    -p 67:67/udp -p 68:68/udp\
    -p 80:80/tcp -p 443:443/tcp -p 443:443/udp -p 3000:3000/tcp\
    -p 853:853/tcp\
    -p 784:784/udp -p 853:853/udp -p 8853:8853/udp\
    -p 5443:5443/tcp -p 5443:5443/udp\
    -d adguard/adguardhome

Need to look how i can make the above into the template at some point :P

**Comment by Macleykun** [comment]
https://github.com/novaspirit/pi-hosted/pull/327

**Comment by Macleykun** [comment]
merged thanks!
