### ISSUE TITLE
[REQUEST] Add --cleanup as CMD argument for watchtower to cleanup images automatically

### ISSUE THREAD

**Issue by Macleykun** [novaspirit/pi-hosted#329]
I'm not sure how to add this.
But i think this would be great as a default, why keep older image versions that only fill's up the system? Especially b/c storage can be limited for some on a pi :).

**Comment by Macleykun** [comment]
^-^

**Comment by blumberg** [comment]
You can use the ENV variable `WATCHTOWER_CLEANUP` set to `true` and it does the trick. To do so you just go to `Duplicate/Edit` and add a variable there (down on the bottom of the page).

I'm not sure if making it the default is a the best, but I can at least send a PR to add the variable for the user to choose.

**Comment by Macleykun** [comment]
> You can use the ENV variable `WATCHTOWER_CLEANUP` set to `true` and it does the trick. To do so you just go to `Duplicate/Edit` and add a variable there (down on the bottom of the page).
> 
> I'm not sure if making it the default is a the best, but I can at least send a PR to add the variable for the user to choose.

Good idea! Didn’t knew they also had it as a env :)

**Comment by rmiddle** [comment]
Option added thanks to blumberg PR.  Clossing.
