### ISSUE TITLE
[QUESTION] Huginn app template web ui not working

### ISSUE THREAD

**Issue by karmarcharger** [novaspirit/pi-hosted#338]
**Question**
Is there any additional scripts to run for the huginn container deployment?

**Context**
Ran the huginn template, tried to open the web UI, unable to access web ui, logs seems to be fine 
![image](https://user-images.githubusercontent.com/10364143/168118077-13ac1ac5-0e87-4370-8d59-8b6e0b5c1263.png)
![image](https://user-images.githubusercontent.com/10364143/168118162-d897fbb1-5f68-4747-ba80-52f795444200.png)

**Comment by Macleykun** [comment]
See: https://github.com/pi-hosted/pi-hosted/issues/26

It's b/c the container image is outdated and the fix is in a newer version.
Personally, i would suggest closing this issue and keeping an eye on here: https://github.com/pi-hosted/pi-hosted/issues/26
