### ISSUE TITLE
[QUESTION] Whoogle has a Permission error

### ISSUE THREAD

**Issue by aindriu80** [novaspirit/pi-hosted#342]
**Question**
Whoogle won't work - it doesn't return a search query, there seems to be a permission error

**Context**
I can view the Whoogle search page but when I enter a query I get the following message:

> Internal Server Error
> The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

In the log files you can see there is some kind of permissions error - see below

````
WARNING:root:Exception raised while handling cache file '/config/session/7de12885929271bf19ef4c37bc58f3ca'

Traceback (most recent call last):

  File "/usr/local/lib/python3.8/site-packages/cachelib/file.py", line 222, in set

    fd, tmp = tempfile.mkstemp(

  File "/usr/local/lib/python3.8/tempfile.py", line 331, in mkstemp

    return _mkstemp_inner(dir, prefix, suffix, flags, output_type)

  File "/usr/local/lib/python3.8/tempfile.py", line 250, in _mkstemp_inner

    fd = _os.open(file, flags, 0o600)

PermissionError: [Errno 13] Permission denied: '/config/session/tmphj74hbyq.__wz_cache'
``````````````````````
I've tried a lot of things like giving permissions, reinstall etc but can't resolve the PermissionError.  Any ideas?

**Comment by martadinata666** [comment]
there is some permission change for older version to new version, the script should help. https://github.com/novaspirit/pi-hosted/blob/457f5de22427313cd4bceb3882f1950bcf6756c6/tools/install_whoogle.sh

**Comment by aindriu80** [comment]
That worked like a treat, thanks !!
