### ISSUE TITLE
[REQUEST] CrowdSec + bouncer Stack

### ISSUE THREAD

**Issue by reikolydia** [novaspirit/pi-hosted#347]
With all these hosted docker services, the moment you open up your network without a good firewall, it might get slammed with unknown/unauthorized requests..

CrowdSec + a bouncer might be useful since it can be used on a pi too.

https://hub.docker.com/r/crowdsecurity/crowdsec

**Comment by Macleykun** [comment]
A pre-run script is needed to get the acquis.yaml. Aswell as changing the path to the yaml file. Perhaps we should change the log location on the host aswell.

docker run -d \
    -v local_path_to_crowdsec_config/acquis.yaml:/etc/crowdsec/acquis.yaml \
    -v crowdsec_config:/etc/crowdsec \
    -v crowdsec_data:/var/lib/crowdsec/data \
    -v /var/log/auth.log:/logs/auth.log:ro \
    -v /var/log/syslog.log:/logs/syslog.log:ro \
    -v /var/log/apache:/logs/apache:ro \
    -e COLLECTIONS="crowdsecurity/apache2 crowdsecurity/sshd" \
    -p 8080:8080 -p 6060:6060 \
    --name crowdsec crowdsecurity/crowdsec
    
the above is how Crowdsec can be run, you happen to have the docker run command to add a bouncer?

**Comment by Macleykun** [comment]
Which bouncer should be used @reikolydia  https://hub.crowdsec.net/browse/#bouncers ?
