### ISSUE TITLE
Is there a fix for Raspberry Pi Docker Monitoring on Pi OS 64 bit?

### ISSUE THREAD

**Issue by moneydontbuyclass** [novaspirit/pi-hosted#353]
**Question**
Is there a fix for Raspberry Pi Docker Monitoring on Pi OS 64 bit? I believe everything works on the 32bit but i would love to get this dashboard working on the new Pi OS 64bit Every statistic for the server shows on Prometheus, Grafana, cAdvisor, NodeExporter stack besides any details on the containers.  I believe it has to do with cAdvisor not being able to read the containers to get info on them. Please advise the on the fix.

**Comment by reikolydia** [comment]
Fix for? It is working fine on my 64bit raspian lite bullseye..

**Comment by Griffen8280** [comment]
Did this get it working for you?  If so feel free to close the ticket out.

**Comment by moneydontbuyclass** [comment]
Yes, it was fixed. You can close out ticket.

**Comment by Griffen8280** [comment]
@rmiddle This ticket can be closed.
