### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by al-jimenez** [novaspirit/pi-hosted#359]
Question
I used Portainer to install Homer and it worked great. I then tried "tiddlywiki", which I have used many years ago. But the container said it installed correctly but is not available. (Used your latest 2022-07-31 portatiner template)

When I checked the log in portainer it said "Error creating directory '/var/lib/tiddlywiki/mywiki'".

My question is did I set up the docker container incorrectly? Any help would be appreciated.

Context
I am running containers / Portainer on Raspberry Pi 4 4GB with updated/upgraded Raspi OS on an SSD.

The installation of the "tiddlywiki" successfully creates the path "/portainer/Files/AppData/Config/TiddlyWiki" and it starts the container shows correct port configs but after a while port configs go away; and container log shows: Error: Error creating directory '/var/lib/tiddlywiki/mywiki'

Any direction you can provide would be appreciated.

I very much appreciate your videos and the progressive topics with RASPI that you cover in them. Keep up the good work!

**Comment by Macleykun** [comment]
> Question I used Portainer to install Homer and it worked great. I then tried "tiddlywiki", which I have used many years ago. But the container said it installed correctly but is not available. (Used your latest 2022-07-31 portatiner template)
> 
> When I checked the log in portainer it said "Error creating directory '/var/lib/tiddlywiki/mywiki'".
> 
> My question is did I set up the docker container incorrectly? Any help would be appreciated.
> 
> Context I am running containers / Portainer on Raspberry Pi 4 4GB with updated/upgraded Raspi OS on an SSD.
> 
> The installation of the "tiddlywiki" successfully creates the path "/portainer/Files/AppData/Config/TiddlyWiki" and it starts the container shows correct port configs but after a while port configs go away; and container log shows: Error: Error creating directory '/var/lib/tiddlywiki/mywiki'
> 
> Any direction you can provide would be appreciated.
> 
> I very much appreciate your videos and the progressive topics with RASPI that you cover in them. Keep up the good work!

This is a permission issue sadly.
I think the best way you could fix this, is by creating a node user on your host machine, make it owner of the /portainer/Files/AppData/Config/TiddlyWiki and then it should be able to write the files it needs.

or, we could make a pre-run script that fills the volume with the needed files and set the right permissions.

**Comment by rmiddle** [comment]
We added an installation script to fix the permission issues.
