### ISSUE TITLE
[REQUEST] Replace "paperless-ng" with "paperless-ngx"

### ISSUE THREAD

**Issue by a73x3434** [novaspirit/pi-hosted#365]
paperless-ng is no longer supported, that's why the community forks it and now operates it under paperless-ngx (https://github.com/paperless-ngx/paperless-ngx)

**Comment by Macleykun** [comment]
This has been done: https://github.com/novaspirit/pi-hosted/blob/master/template/apps/paperless-ngx.json :)

**Comment by rmiddle** [comment]
Paperless-ngx has been added and paperless-ng has been removed.
