### ISSUE TITLE
Armhf Support ending for Sonarr

### ISSUE THREAD

**Issue by Griffen8280** [novaspirit/pi-hosted#369]
Per the articles from the linuxserver team here:
https://info.linuxserver.io/issues/2022-08-02-sonarr/

And their support table located on the Docker hub here:
https://hub.docker.com/r/linuxserver/sonarr

It would appear 32-bit versions of sonarr will no longer be built past version 3.0.8.1507-ls151.  I have verified that this information is accurate when I could no longer update sonarr on my Pi-4 running the 32bit Raspbian OS.  I have since upgraded the Pis OS to the 64bit bullseye base, but it may be prudent to remove the "image_arm32": "linuxserver/sonarr:latest" line from the sonarr.json file.  If you approve I can do that easily enough and submit a pull request.

@rmiddle

**Comment by rmiddle** [comment]
I just removed support for 32bit.
