### ISSUE TITLE
Transmission-IPVanish

### ISSUE THREAD

**Issue by Foresaken1** [novaspirit/pi-hosted#393]
I've been using transmission with ipvanish since the video went live on youtube with no issues. then suddenly it stopped working. it would always say starting but never actually start. I redid everything thinking it would work again like it did before and nope. 

this is what it started doing

      
Provider IPVANISH has a custom setup script, executing it
Downloading OpenVPN config bundle configs.zip into temporary file /tmp/tmp.noMfIe
Extract OpenVPN config bundle into /etc/openvpn/ipvanish
unzip: short read
Starting container with revision: 47f32618629b0144f492b9116f77978d4c991712
Creating TUN device /dev/net/tun
mknod: /dev/net/tun: File exists
Using OpenVPN provider: IPVANISH
Provider IPVANISH has a custom setup script, executing it
Downloading OpenVPN config bundle configs.zip into temporary file /tmp/tmp.MlOflc
Extract OpenVPN config bundle into /etc/openvpn/ipvanish
unzip: short read
Starting container with revision: 47f32618629b0144f492b9116f77978d4c991712
Creating TUN device /dev/net/tun
mknod: /dev/net/tun: File exists
Using OpenVPN provider: IPVANISH
Provider IPVANISH has a custom setup script, executing it
Downloading OpenVPN config bundle configs.zip into temporary file /tmp/tmp.JnfcNG
Extract OpenVPN config bundle into /etc/openvpn/ipvanish
unzip: short read
Starting container with revision: 47f32618629b0144f492b9116f77978d4c991712
Creating TUN device /dev/net/tun
mknod: /dev/net/tun: File exists
Using OpenVPN provider: IPVANISH
Provider IPVANISH has a custom setup script, executing it
Downloading OpenVPN config bundle configs.zip into temporary file /tmp/tmp.kBbIjm
Extract OpenVPN config bundle into /etc/openvpn/ipvanish
unzip: short read
Starting container with revision: 47f32618629b0144f492b9116f77978d4c991712
Creating TUN device /dev/net/tun
mknod: /dev/net/tun: File exists
Using OpenVPN provider: IPVANISH
Provider IPVANISH has a custom setup script, executing it
Downloading OpenVPN config bundle configs.zip into temporary file /tmp/tmp.obDcnD
Extract OpenVPN config bundle into /etc/openvpn/ipvanish
unzip: short read
Starting container with revision: 47f32618629b0144f492b9116f77978d4c991712
Creating TUN device /dev/net/tun
mknod: /dev/net/tun: File exists
Using OpenVPN provider: IPVANISH
Provider IPVANISH has a custom setup script, executing it
Downloading OpenVPN config bundle configs.zip into temporary file /tmp/tmp.GBJCkM
Extract OpenVPN config bundle into /etc/openvpn/ipvanish
unzip: short read
Starting container with revision: 47f32618629b0144f492b9116f77978d4c991712
Creating TUN device /dev/net/tun
mknod: /dev/net/tun: File exists
Using OpenVPN provider: IPVANISH
Provider IPVANISH has a custom setup script, executing it
Downloading OpenVPN config bundle configs.zip into temporary file /tmp/tmp.jalBKG
Extract OpenVPN config bundle into /etc/openvpn/ipvanish
unzip: short read
Starting container with revision: 47f32618629b0144f492b9116f77978d4c991712
Creating TUN device /dev/net/tun
mknod: /dev/net/tun: File exists
Using OpenVPN provider: IPVANISH
Provider IPVANISH has a custom setup script, executing it
Downloading OpenVPN config bundle configs.zip into temporary file /tmp/tmp.CKLkFd
Extract OpenVPN config bundle into /etc/openvpn/ipvanish
unzip: short read
Starting container with revision: 47f32618629b0144f492b9116f77978d4c991712
Creating TUN device /dev/net/tun
mknod: /dev/net/tun: File exists
Using OpenVPN provider: IPVANISH
Provider IPVANISH has a custom setup script, executing it
Downloading OpenVPN config bundle configs.zip into temporary file /tmp/tmp.Gnenhk
Extract OpenVPN config bundle into /etc/openvpn/ipvanish
unzip: short read
Starting container with revision: 47f32618629b0144f492b9116f77978d4c991712
Creating TUN device /dev/net/tun
mknod: /dev/net/tun: File exists
Using OpenVPN provider: IPVANISH
Provider IPVANISH has a custom setup script, executing it
Downloading OpenVPN config bundle configs.zip into temporary file /tmp/tmp.NIaLAO
Extract OpenVPN config bundle into /etc/openvpn/ipvanish
unzip: short read
Starting container with revision: 47f32618629b0144f492b9116f77978d4c991712
Creating TUN device /dev/net/tun
mknod: /dev/net/tun: File exists
Using OpenVPN provider: IPVANISH
Provider IPVANISH has a custom setup script, executing it
Downloading OpenVPN config bundle configs.zip into temporary file /tmp/tmp.ceEpDO
Extract OpenVPN config bundle into /etc/openvpn/ipvanish
unzip: short read
Starting container with revision: 47f32618629b0144f492b9116f77978d4c991712
Creating TUN device /dev/net/tun
mknod: /dev/net/tun: File exists
Using OpenVPN provider: IPVANISH
Provider IPVANISH has a custom setup script, executing it
Downloading OpenVPN config bundle configs.zip into temporary file /tmp/tmp.AKgloM
Extract OpenVPN config bundle into /etc/openvpn/ipvanish
unzip: short read
Starting container with revision: 47f32618629b0144f492b9116f77978d4c991712
Creating TUN device /dev/net/tun
mknod: /dev/net/tun: File exists
Using OpenVPN provider: IPVANISH
Provider IPVANISH has a custom setup script, executing it
Downloading OpenVPN config bundle configs.zip into temporary file /tmp/tmp.BKHkac
Extract OpenVPN config bundle into /etc/openvpn/ipvanish
unzip: short read

**Comment by Macleykun** [comment]
what's the name of the application in the template list?
