### ISSUE TITLE
Creating Samba on a Raspi 64bit, fails

### ISSUE THREAD

**Issue by Redback813** [novaspirit/pi-hosted#394]
I like to say thank you so much for all the hard work you put in with these projects.

System Settings
Linux Raspberry Pi 5.15.61-v8+ #1579 SMP PREEMPT
Name="Debian GNU/Linux"
Version_ID="11"
Version="11 (Bullseye)"
Version_Codename=Bullseye

macOS = Big Sur

#############################

  I installed a fresh OS on Raspberry Pi with the Bullseye 64bit with no issues, the system is setup with pi-hole and unbound with no issue, I then installed your docker and portainer sh commands from your site in the macOS terminal windows connected to Raspberry Pi with no issues.
 I decided to start with samba and install as default setting and that is far as far as it gets, in the container it reads created and yet in your video it is green and running, so what am I missing.

![image](https://user-images.githubusercontent.com/54433630/194446227-c23f18fc-2c9b-4740-a53c-e372e226bf1f.png)
 Any help would be appreciated.

Thanks in advance

**Comment by martadinata666** [comment]
Try manually run the container via terminal, likely it conflicting with OS installed samba.
```
docker start Samba
```

**Comment by Redback813** [comment]
pi@raspberrypi:~ $ docker start Samba
Error response from daemon: driver failed programming external connectivity on endpoint Samba (0e18b778f592715f8cd04a49aab4260f7826b8339af7d80da594ae3f0a8e7fdb): Error starting userland proxy: listen tcp4 0.0.0.0:445: bind: address already in use
Error: failed to start containers: Samba
pi@raspberrypi:~ $

**Comment by Redback813** [comment]
If I have samba installed in Bullseye OS, do I still need within the container to access external NAS drives?

**Comment by martadinata666** [comment]
No, choose one system installed or docker container method.

**Comment by Redback813** [comment]
I'll uninstall the docker.

Cheers
