### ISSUE TITLE
Whoogle fails to start on Raspi 64bit

### ISSUE THREAD

**Issue by WoefulWrecker** [novaspirit/pi-hosted#395]
System Settings
Linux Raspberry Pi 5.15.61-v8+ #1579 SMP PREEMPT
Name="Debian GNU/Linux"
Version_ID="11"
Version="11 (Bullseye)"
Version_Codename=Bullseye

macOS = Big Sur

#############################

Whoogle installed without any known issues in portainer, however failure to retain an IP address after 60sec shows sign of problems, hence I'm providing the log file of the issues.

![image](https://user-images.githubusercontent.com/54433630/194448987-093c2cad-0620-432c-8587-ff4140a1916e.png)

[_whoogle_logs.txt](https://github.com/novaspirit/pi-hosted/files/9730082/_whoogle_logs.txt)

Thanks in advance

**Comment by martadinata666** [comment]
Did you run preinstall script?

**Comment by Redback813** [comment]
Sorry, didn't see that little nugget, all's working fine for whoogle.

It seems I can't change settings in SearXNG in any browser on the macOS, but I can change settings in Whoogle in the browser on the macOS? Any clue to look at?
It's not a proxy issue.

**Comment by Macleykun** [comment]
> Sorry, didn't see that little nugget, all's working fine for whoogle.
> 
> It seems I can't change settings in SearXNG in any browser on the macOS, but I can change settings in Whoogle in the browser on the macOS? Any clue to look at? It's not a proxy issue.

I think it's better to use whoogle instead of SearXNG in that case, if there's a problem with SearXNG itself i would advice opening an issue there :-)
