### ISSUE TITLE
[QUESTION] Whoogle search behaviour

### ISSUE THREAD

**Issue by WoefulWrecker** [novaspirit/pi-hosted#399]
**Question**
Your question here.

When doing a search on Whoogle is it normal for the search engine to ask which search site to use, when I watched your whoogle video usage this behaviour never occurs. 

![image](https://user-images.githubusercontent.com/54433630/196128528-c2260e23-3b5d-411e-bf3c-ed1269784a08.png)

**Context**
Any additional context around the question, such a link to a project where it's being implemented.

Whoogle search operates on Raspberry P in docker, but the search is done in the Brave browser on the macOS.

**Comment by rmiddle** [comment]
Are you running this on Arm32 or Arm64?

**Comment by Redback813** [comment]
Running Arm64 Raspberry Pi 4B, Bulleyes OS
Linux raspberrypi 5.15.76-v8+ #1597 SMP

Thanks in advance

**Comment by Macleykun** [comment]
I think it's related to this issue:
https://github.com/benbusby/whoogle-search/issues/707
