### ISSUE TITLE
[QUESTION] Deluge installation failure

### ISSUE THREAD

**Issue by Redback813** [novaspirit/pi-hosted#400]
**Question**
Installing the Deluge in portainer, only it fails with an error msg:
Failure
Request failed with status code 500

“System”
Raspberry Pi 4B
Bullseye 64bit

**Context**
Any additional context around the question, such a link to a project where it's being implemented.

**Comment by Macleykun** [comment]
![image](https://user-images.githubusercontent.com/26381427/202872924-7a01abf0-16a2-43bc-bc80-e92398b4f83a.png)
deluge is working as expected

**Comment by rmiddle** [comment]
Stale.  Closing.
