### ISSUE TITLE
[REQUEST] Rocket Chat

### ISSUE THREAD

**Issue by davistroy** [novaspirit/pi-hosted#404]
https://www.rocket.chat/install

**Comment by rmiddle** [comment]
Rocket Chat is commercial software not adding.

**Comment by davistroy** [comment]
Huh??

It says right on the web site:

“The world's largest open source communications platform". ... see screenshot attached.

—
Troy Davis

________________________________

**Comment by davistroy** [comment]
https://www.rocket.chat/enterprise/open-source


—
Troy Davis

________________________________
