### ISSUE TITLE
Import fails on AMD64 Debian 11 host running Portainer Community Edition 2.16.1

### ISSUE THREAD

**Issue by Steve-Vallis** [novaspirit/pi-hosted#407]
failed to deploy a stack: time="2022-11-17T23:32:07Z" level=warning msg="The \"RT_DHT_PORT\" variable is not set. Defaulting to a blank string." time="2022-11-17T23:32:07Z" level=warning msg="The \"RT_DHT_PORT\" variable is not set. Defaulting to a blank string." time="2022-11-17T23:32:07Z" level=warning msg="The \"XMLRPC_PORT\" variable is not set. Defaulting to a blank string." time="2022-11-17T23:32:07Z" level=warning msg="The \"XMLRPC_PORT\" variable is not set. Defaulting to a blank string." time="2022-11-17T23:32:07Z" level=warning msg="The \"RUTORRENT_PORT\" variable is not set. Defaulting to a blank string." time="2022-11-17T23:32:07Z" level=warning msg="The \"RUTORRENT_PORT\" variable is not set. Defaulting to a blank string." time="2022-11-17T23:32:07Z" level=warning msg="The \"WEBDAV_PORT\" variable is not set. Defaulting to a blank string." time="2022-11-17T23:32:07Z" level=warning msg="The \"WEBDAV_PORT\" variable is not set. Defaulting to a blank string." time="2022-11-17T23:32:07Z" level=warning msg="The \"RT_INC_PORT\" variable is not set. Defaulting to a blank string." time="2022-11-17T23:32:07Z" level=warning msg="The \"RT_INC_PORT\" variable is not set. Defaulting to a blank string." invalid interpolation format for templates.[].note. You may need to escape any $ with another $. <h3>Template created by Pi-Hosted Series</h3><b>Check our Github page: <a href="https://github.com/pi-hosted/pi-hosted" target="_blank">https://github.com/pi-hosted/pi-hosted</a></b><br><br><b>Official Webpage: </b><a href="https://github.com/Novik/ruTorrent" target="_blank">https://github.com/Novik/ruTorrent</a><br><b>Official Docker Documentation: </b><a href="https://github.com/crazy-max/docker-rtorrent-rutorrent" target="_blank">https://github.com/crazy-max/docker-rtorrent-rutorrent</a><br><br><br>For ruTorrent basic auth, XMLRPC through nginx and WebDAV on completed downloads, you can populate .htpasswd files with the following command:\ndocker run --rm -it httpd:2.4-alpine htpasswd -Bbn <username> <password> >> $(pwd)/passwd/webdav.htpasswd

**Comment by rmiddle** [comment]
The errors suggest you didn't make sure all the fields had something filed in.
