### ISSUE TITLE
NextcloudPi blank page - pihosted container - RPI OS 64 bits

### ISSUE THREAD

**Issue by Tchiimy** [novaspirit/pi-hosted#408]
Hello,

I'm running NextcloudPi (docker ARM version), on a RPI4.

After the update of this container it seems that the NextcloudPi interface is "blank' :

![image](https://user-images.githubusercontent.com/75799578/205610747-b70bf32a-f24f-4542-a9bf-84163afcc508.png)

It seems to be something similar to [this](https://github.com/nextcloud/nextcloudpi/issues/287#issuecomment-343726717) but I don't know if someone had the same problem with the docker version.

Nextcloud is always in maintenance mode and I can do nothing on the NextcloudPi interface, I'm locked and I don't really understand why.

Any ideas ?

**Comment by Macleykun** [comment]
It seems you were able to fix this problem by 
sudo nano /portainer/Files/AppData/Config/ncdata/nextcloud/config/config.php

'maintenance' => false

I assume nobody else has had this problem

**Comment by Tchiimy** [comment]
> It seems you were able to fix this problem by sudo nano /portainer/Files/AppData/Config/ncdata/nextcloud/config/config.php
> 
> 'maintenance' => false
> 
> I assume nobody else has had this problem

Yeah but I still to have the NextcloudPi interface "locked" 

![image](https://user-images.githubusercontent.com/75799578/209002257-b4caa436-4e70-4093-bb8f-dec6af9d13fa.png)

Should I use a command to force the update of nextcloudpi to the newest version ?

**Comment by Macleykun** [comment]
Yes for sure :) !
Is there also anything in the console on the webpage (f12) or in the container logs?
________________________________
Van: Tchiimy ***@***.***>
Verzonden: Wednesday, December 21, 2022 10:03:34 PM
Aan: novaspirit/pi-hosted ***@***.***>
CC: Macley ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [novaspirit/pi-hosted] NextcloudPi blank page - pihosted container - RPI OS 64 bits (Issue #408)


It seems you were able to fix this problem by sudo nano /portainer/Files/AppData/Config/ncdata/nextcloud/config/config.php

'maintenance' => false

I assume nobody else has had this problem

Yeah but I still to have the NextcloudPi interface "locked"

[image]<https://user-images.githubusercontent.com/75799578/209002257-b4caa436-4e70-4093-bb8f-dec6af9d13fa.png>

Should I use a command to force the update of nextcloudpi to the newest version ?

**Comment by Tchiimy** [comment]
> Yes for sure :) ! Is there also anything in the console on the webpage (f12) or in the container logs?

I don't know if it's help but i have this when I press F12 (webpage): 
![image](https://user-images.githubusercontent.com/75799578/209100889-c98b2adb-2c05-46d1-a786-c0dedc58dea9.png)



Which command should I use to try to update NCP ?

**Comment by Macleykun** [comment]
Hmm, interesting so I think the errors are probably bc there’s smth wrong in the app itself (csp is not smth you thinker with, rather the developer securing the website does), I’m more inclined to think that an update might fix it.

You can stop and then remove the container and you can use docker pull linuxserver/nextcloud:latest
Then ya can recreate the container again from the template.
All the files that were saved in your volumes/mounts will be saved, the rest doesn’t.
________________________________
Van: Tchiimy ***@***.***>
Verzonden: Thursday, December 22, 2022 10:18:55 AM
Aan: novaspirit/pi-hosted ***@***.***>
CC: Macley ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [novaspirit/pi-hosted] NextcloudPi blank page - pihosted container - RPI OS 64 bits (Issue #408)


Yes for sure :) ! Is there also anything in the console on the webpage (f12) or in the container logs?

I don't know if it's help but i have this when I press F12 (webpage):
[image]<https://user-images.githubusercontent.com/75799578/209100889-c98b2adb-2c05-46d1-a786-c0dedc58dea9.png>

Which command should I use to try to update NCP ?
