### ISSUE TITLE
Typo in Jellyfin's volume path

### ISSUE THREAD

**Issue by BaderMaiss** [novaspirit/pi-hosted#410]
## Issue
Small typo in the volume path of Jellyfin and Jellyfin-Accounts in all templates. The name of the folder is "Jelllyfin" instead of "Jellyfin".
## Code preview on all templates
`"volumes": [
				{
					"bind": "/portainer/Files/AppData/Config/Jelllyfin",
					"container": "/config"
				}...`

**Comment by rmiddle** [comment]
Typo in path fixed and pushed live.
