### ISSUE TITLE
Error using upgrade script provided on Banana Pi

### ISSUE THREAD

**Issue by CLAYJFR05** [novaspirit/pi-hosted#417]
pi@BananaPi:~ $ wget -qO- https://raw.githubusercontent.com/pi-hosted/pi-hosted/master//tools/update_libseccomp2.sh | bash
Checking if you are online...Online. Continuing.
Libseccomp2 upgrade needed if you run rpi 32bit. Check version with 'dpkg-query -W libseccomp'. if the version is 2.3 or below, this script is necessary.
--2023-01-14 09:03:39--  http://ftp.us.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.5.4-1+b1_armhf.deb
Resolving ftp.us.debian.org (ftp.us.debian.org)... 64.50.233.100, 208.80.154.139, 64.50.236.52, ...
Connecting to ftp.us.debian.org (ftp.us.debian.org)|64.50.233.100|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-01-14 09:03:40 ERROR 404: Not Found.

Failed to download libseccomp2.deb

**Comment by valyrian84** [comment]
I am facing the same issue

pi@pi-srv01:~/downloads/pi-hosted $ wget -qO- https://raw.githubusercontent.com/pi-hosted/pi-hosted/master//tools/update_libseccomp2.sh | bash
Checking if you are online...Online. Continuing.
Libseccomp2 upgrade needed if you run rpi 32bit. Check version with 'dpkg-query -W libseccomp'. if the version is 2.3 or below, this script is necessary.
--2023-01-18 21:36:14--  http://ftp.us.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.5.4-1+b1_armhf.deb
Resolving ftp.us.debian.org (ftp.us.debian.org)... 208.80.154.139, 64.50.233.100, 64.50.236.52, ...
Connecting to ftp.us.debian.org (ftp.us.debian.org)|208.80.154.139|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-01-18 21:36:14 ERROR 404: Not Found.

Failed to download libseccomp2.deb

**Comment by rmiddle** [comment]
I can check the version info but Banana Pi isn't tested.

**Comment by rmiddle** [comment]
Fixed the script.  Still not sure about Banana Pi but this script is fixed.

**Comment by Macleykun** [comment]
@CLAYJFR05 is the issue resolved for you? If so, could you please close the issue :) ?
