### ISSUE TITLE
App template not working 

### ISSUE THREAD

**Issue by valyrian84** [novaspirit/pi-hosted#418]
I am running 32bit Pi OS. I updated the Portainer and since then by App template stopped working.  

Error - Get "https://raw.githubusercontent.com/pi-hosted/pi-hosted/master/template/portainer-v2-arm32.json": dial tcp: lookup raw.githubusercontent.com on *.*.20.*:53: read udp 172.17.0.3:49733->*.*.20.*:53: i/o timeout

pi@pi-srv01:~ $ uname -m
armv7l

**Comment by valyrian84** [comment]
Updated/Upgraded the host, rebooted and pulled the latest update_portainer sheel script. Still no luck.

**Comment by Macleykun** [comment]
Looking the exact problem up in google:
https://github.com/docker/for-mac/issues/1569
So it seems rather it's not the template not working, rather it seems to be a DNS issue on your end.
Also: https://www.reddit.com/r/portainer/comments/yw296v/cant_get_app_templates_getting_io_timeout/

Could you... stop the container, delete it and then start over with the portainer bit?
Can you also provide more infor about your setup (specifically related to DNS)

**Comment by valyrian84** [comment]
Thanks a lot @Macleykun You pointed me in the right direction. The Pihole (which is installed in the same Pi as a container) was blocking the domain. Whitelisted the regex and voila!

**Comment by Macleykun** [comment]
awsome :D !
could ya close the issue then?

**Comment by valyrian84** [comment]
Absolutely. Thanks!
