### ISSUE TITLE
[Port and ip address not displayes on Homer]

### ISSUE THREAD

**Issue by ndg2806** [novaspirit/pi-hosted#419]
**Issue**
Ip address and Port ids not displayed on Homer.

**Context**
I have been using Pi-hosted series to install Docker/Portainer. after Portainer i have installed Homer from suggested Template, Homer is **running** but not showing any Port ids or Ip address. I have raised query at Homer Github but no reply as of now. see this link https://github.com/bastienwirtz/homer/issues/592#issue-1552077110

**Comment by Macleykun** [comment]
Heya, i think you've missed one step that has to be done beforehand.
![image](https://user-images.githubusercontent.com/26381427/214933170-b8667291-487f-4264-9e88-2a765f6182ec.png)

Can you try to run this first, and then reboot the container?
```
wget -qO- https://raw.githubusercontent.com/pi-hosted/pi-hosted/master/tools/install_homer.sh | bash
```

then you can start creating your own homer by editting the config file:
```
vim /portainer/Files/AppData/Config/Homer/assets/config.yml
```

**Comment by ndg2806** [comment]
Thanks, your suggestion helped. all gud now.

![image](https://user-images.githubusercontent.com/74371184/215329010-71e876b4-0583-468b-b85a-1b7af7a15d2e.png)
