### ISSUE TITLE
curl: (6) Could not resolve host: http://www.duckdns.org

### ISSUE THREAD

**Issue by valyrian84** [novaspirit/pi-hosted#421]
Just installed the Duckdns container from the app template filling in the subdomain & token but getting the error - 

**_curl: (6) Could not resolve host: http://www.duckdns.org/_** 

`Retrieving subdomain and token from the environment variables
log will be output to docker log
curl: (6) Could not resolve host: www.duckdns.org
Something went wrong, please check your settings Sun Feb  5 11:29:34 EST 2023
The response returned was:
[custom-init] No custom files found, skipping...
[ls.io-init] done.
curl: (6) Could not resolve host: www.duckdns.org
Something went wrong, please check your settings Sun Feb  5 11:33:04 EST 2023
The response returned was:
curl: (6) Could not resolve host: www.duckdns.org
Something went wrong, please check your settings Sun Feb  5 11:38:38 EST 2023
The response returned was:
curl: (6) Could not resolve host: www.duckdns.org
Something went wrong, please check your settings Sun Feb  5 11:43:42 EST 2023
The response returned was:
[custom-init] No custom services found, skipping...
[migrations] started
[migrations] no migrations found
usermod: no changes
-------------------------------------`

Since I have a PiHole in my network, I disabled blocking, bypassed PiHole and had by DNS set to 1.1.1.1 & 8.8.8.8 for the network to which the Pi host is connected to. Still no luck.

Its able to resolve other known FQDNs but www.duckdns.org

From my Pi -
pi@pi-srv01:~ $ dig pimylifeup.com

; <<>> DiG 9.16.37-Raspbian <<>> pimylifeup.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 40105
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;pimylifeup.com.                        IN      A

;; ANSWER SECTION:
pimylifeup.com.         300     IN      A       104.26.4.41
pimylifeup.com.         300     IN      A       104.26.5.41
pimylifeup.com.         300     IN      A       172.67.73.232

;; Query time: 20 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: Sun Feb 05 11:48:04 EST 2023
;; MSG SIZE  rcvd: 91
======
pi@pi-srv01:~ $ ping www.duckdns.org
PING appservers-duckdns-prod-1630339571.ca-central-1.elb.amazonaws.com (15.222.164.95) 56(84) bytes of data.
^C
--- appservers-duckdns-prod-1630339571.ca-central-1.elb.amazonaws.com ping statistics ---
8 packets transmitted, 0 received, 100% packet loss, time 7254ms
======
pi@pi-srv01:~ $ ping www.google.com
PING www.google.com (142.251.40.132) 56(84) bytes of data.
64 bytes from lga25s80-in-f4.1e100.net (142.251.40.132): icmp_seq=1 ttl=116 time=11.4 ms
64 bytes from lga25s80-in-f4.1e100.net (142.251.40.132): icmp_seq=2 ttl=116 time=13.7 ms
64 bytes from lga25s80-in-f4.1e100.net (142.251.40.132): icmp_seq=3 ttl=116 time=12.0 ms
^C
--- www.google.com ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2003ms
rtt min/avg/max/mdev = 11.443/12.388/13.677/0.943 ms
======
From my PC -
Wireless LAN adapter Wi-Fi:

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Intel(R) Wireless-AC 9560 160MHz
   Physical Address. . . . . . . . . : XX-XX-XX-XX-X8-FA
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : xxxx::xxxx:xxxx:499c:6cfd%8(Preferred)
   IPv4 Address. . . . . . . . . . . : 192.168.20.64(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Lease Obtained. . . . . . . . . . : Sunday, February 5, 2023 10:35:01 AM
   Lease Expires . . . . . . . . . . : Monday, February 6, 2023 10:35:00 AM
   Default Gateway . . . . . . . . . : 192.168.20.1
   DHCP Server . . . . . . . . . . . : 192.168.20.1
   DHCPv6 IAID . . . . . . . . . . . : 76867319
   DHCPv6 Client DUID. . . . . . . . : 00-01-00-01-28-62-82-4D-F8-75-A4-04-60-7D
   DNS Servers . . . . . . . . . . . : 1.1.1.1
                                       8.8.8.8
   NetBIOS over Tcpip. . . . . . . . : Enabled
======
ping www.duckdns.org

Pinging appservers-duckdns-prod-1630339571.ca-central-1.elb.amazonaws.com [3.97.46.78] with 32 bytes of data:
Request timed out.
Request timed out.

Ping statistics for 3.97.46.78:
    Packets: Sent = 2, Received = 0, Lost = 2 (100% loss),
======
ping www.google.com

Pinging www.google.com [142.251.40.228] with 32 bytes of data:
Reply from 142.251.40.228: bytes=32 time=13ms TTL=116
Reply from 142.251.40.228: bytes=32 time=11ms TTL=116
Reply from 142.251.40.228: bytes=32 time=16ms TTL=116
Reply from 142.251.40.228: bytes=32 time=18ms TTL=116

Ping statistics for 142.251.40.228:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
======
ping cnn.com

Pinging cnn.com [151.101.67.5] with 32 bytes of data:
Reply from 151.101.67.5: bytes=32 time=12ms TTL=55
Reply from 151.101.67.5: bytes=32 time=16ms TTL=55
Reply from 151.101.67.5: bytes=32 time=15ms TTL=55
Reply from 151.101.67.5: bytes=32 time=15ms TTL=55

Ping statistics for 151.101.67.5:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 12ms, Maximum = 16ms, Average = 14ms

I would really appreciate if someone can guide me in the right direction here.

**Comment by valyrian84** [comment]
This is resolved. Had to add public nameservers to resolv.conf. Not sure why I had to do it even though the PiHole was redirecting the DNS requests to the same public resolvers.

**Comment by rmiddle** [comment]
> This is resolved. Had to add public nameservers to resolv.conf. Not sure why I had to do it even though the PiHole was redirecting the DNS requests to the same public resolvers.

Is PiHole on the same system as this container?  If so that is a DNS/Routing issue that is well known.  https://blog.albony.xyz/posts/dns-docker/
