### ISSUE TITLE
Typo on  pi-hosted/tools/install_whoogle.sh 

### ISSUE THREAD

**Issue by robbpaulsen** [novaspirit/pi-hosted#429]
Hi,

I was just configuring my portainer setup but since its on a Fedora Workstation i have to make the proper adjustments, and I noticed on the whooshle.sh file has a typo on line 23:

sudo chown -R 927.927 /portainer/Files/AppData/Config/Whoogle || error "Failed to set permissions!"

The script will never end well because of the " . " it's expecting a " : " between the permission numbers, that's it.

Thanks and have a nice day.

**Comment by rmiddle** [comment]
Although the script worked fine in Debian I can see using something no standard isn't a good thing.  Someone submitted a patch back in March and was accepted, so closing this now.
