### ISSUE TITLE
[REQUEST] speedtest-tracker is abandoned

### ISSUE THREAD

**Issue by idoodler** [novaspirit/pi-hosted#430]
**Is your feature request related to a problem? Please describe.**
It appears as if [speedtest-tracker](https://github.com/henrywhitaker3/Speedtest-Tracker) is abandoned.

**Describe the solution you'd like**
There is a new project which aims to have feature parity which also looks very beautiful:  https://github.com/alexjustesen/speedtest-tracker-docs

**Describe alternatives you've considered**
Using the above mentioned image

**Comment by rmiddle** [comment]
Looks like a good framework / design will need to look into this.
