### ISSUE TITLE
This label seems inconsistent.

### ISSUE THREAD

**Issue by CactusBadger** [novaspirit/pi-hosted#450]
https://github.com/novaspirit/pi-hosted/blob/ff6f0555519c586c69ec269439ec48945c559023/template/apps/minecraft-server.json#LL25C3-L25C17

Says "restart_polocy", references in other files say "restart_policy".

There are multiple occurrences of "restart_polocy" in the repo.

**Comment by ncksnydr** [comment]
Obviously sounds like a typo. Why not fix the bug yourself and do a PR?

**Comment by CactusBadger** [comment]
I wasn't sure of the etiquette. I'll get onto that as soon  as I can.

**Comment by EduKap** [comment]
This should solve it: #458
