### ISSUE TITLE
[REQUEST] please add wallabag 

### ISSUE THREAD

**Issue by githubxnoob** [novaspirit/pi-hosted#455]
wallabag is an open source application to save your web articles and allows you to read them later, on your smartphone, your tablet or your e-reader.

wallabag is a selfhosted alternative to pocket. 

they have arm images on dockerhub

https://www.wallabag.it/en

https://hub.docker.com/r/wallabag/wallabag

https://github.com/wallabag/wallabag

**Comment by SlimPugGamer** [comment]
can't you just fork this repo and add it

**Comment by JohnAOSC** [comment]
@githubxnoob I've made a pull request for this if you'd like to try it out and give me your feedback while we wait for it to be officially added.😉
