### ISSUE TITLE
Raspberry Pi Monitoring Using Grafana and Prometheus Does not work After raspberry restart

### ISSUE THREAD

**Issue by singh0192** [novaspirit/pi-hosted#476]
This is the logs grafana logs:

logger=settings t=2023-11-26T15:29:11.74567827Z level=info msg="Config loaded from" file=/etc/grafana/grafana.ini
logger=settings t=2023-11-26T15:29:11.745692639Z level=info msg="Config overridden from command line" arg="default.paths.data=/var/lib/grafana"
logger=settings t=2023-11-26T15:29:11.745705139Z level=info msg="Config overridden from command line" arg="default.paths.logs=/var/log/grafana"
logger=settings t=2023-11-26T15:29:11.74571712Z level=info msg="Config overridden from command line" arg="default.paths.plugins=/var/lib/grafana/plugins"
logger=settings t=2023-11-26T15:29:11.74573323Z level=info msg="Config overridden from command line" arg="default.paths.provisioning=/etc/grafana/provisioning"
logger=settings t=2023-11-26T15:29:11.745780654Z level=info msg="Config overridden from command line" arg="default.log.mode=console"
logger=settings t=2023-11-26T15:29:11.74579606Z level=info msg="Config overridden from Environment variable" var="GF_PATHS_DATA=/var/lib/grafana"
logger=settings t=2023-11-26T15:29:11.745808838Z level=info msg="Config overridden from Environment variable" var="GF_PATHS_LOGS=/var/log/grafana"
logger=settings t=2023-11-26T15:29:11.745821041Z level=info msg="Config overridden from Environment variable" var="GF_PATHS_PLUGINS=/var/lib/grafana/plugins"
logger=settings t=2023-11-26T15:29:11.745855928Z level=info msg="Config overridden from Environment variable" var="GF_PATHS_PROVISIONING=/etc/grafana/provisioning"
logger=settings t=2023-11-26T15:29:11.745871687Z level=info msg="Config overridden from Environment variable" var="GF_USERS_ALLOW_SIGN_UP=false"
logger=settings t=2023-11-26T15:29:11.745889889Z level=info msg=Target target=[all]
logger=settings t=2023-11-26T15:29:11.745944109Z level=info msg="Path Home" path=/usr/share/grafana
logger=settings t=2023-11-26T15:29:11.745959553Z level=info msg="Path Data" path=/var/lib/grafana
logger=settings t=2023-11-26T15:29:11.745971775Z level=info msg="Path Logs" path=/var/log/grafana
logger=settings t=2023-11-26T15:29:11.745983718Z level=info msg="Path Plugins" path=/var/lib/grafana/plugins
logger=settings t=2023-11-26T15:29:11.745995699Z level=info msg="Path Provisioning" path=/etc/grafana/provisioning
logger=settings t=2023-11-26T15:29:11.746030272Z level=info msg="App mode production"
logger=sqlstore t=2023-11-26T15:29:11.746895732Z level=info msg="Connecting to DB" dbtype=sqlite3
logger=sqlstore t=2023-11-26T15:29:11.746942767Z level=warn msg="SQLite database file has broader permissions than it should" path=/var/lib/grafana/grafana.db mode=-rw-rw-r-- expected=-rw-r-----
logger=migrator t=2023-11-26T15:29:11.748538508Z level=info msg="Starting DB migrations"
Error: ✗ failed to check table existence: attempt to write a readonly database
GF_PATHS_DATA='/var/lib/grafana' is not writable.
You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migrate-to-v51-or-later
logger=settings t=2023-11-26T15:29:13.692635337Z level=info msg="Starting Grafana" version=10.2.2 commit=161e3cac5075540918e3a39004f2364ad104d5bb branch=HEAD compiled=2023-11-20T12:28:00Z
logger=settings t=2023-11-26T15:29:13.693358378Z level=info msg="Config loaded from" file=/usr/share/grafana/conf/defaults.ini
logger=settings t=2023-11-26T15:29:13.69340095Z level=info msg="Config loaded from" file=/etc/grafana/grafana.ini
logger=settings t=2023-11-26T15:29:13.693415672Z level=info msg="Config overridden from command line" arg="default.paths.data=/var/lib/grafana"
logger=settings t=2023-11-26T15:29:13.693427727Z level=info msg="Config overridden from command line" arg="default.paths.logs=/var/log/grafana"
logger=settings t=2023-11-26T15:29:13.693439874Z level=info msg="Config overridden from command line" arg="default.paths.plugins=/var/lib/grafana/plugins"
logger=settings t=2023-11-26T15:29:13.693454559Z level=info msg="Config overridden from command line" arg="default.paths.provisioning=/etc/grafana/provisioning"
logger=settings t=2023-11-26T15:29:13.693467466Z level=info msg="Config overridden from command line" arg="default.log.mode=console"
logger=settings t=2023-11-26T15:29:13.693480132Z level=info msg="Config overridden from Environment variable" var="GF_PATHS_DATA=/var/lib/grafana"
logger=settings t=2023-11-26T15:29:13.693493279Z level=info msg="Config overridden from Environment variable" var="GF_PATHS_LOGS=/var/log/grafana"
logger=settings t=2023-11-26T15:29:13.693505445Z level=info msg="Config overridden from Environment variable" var="GF_PATHS_PLUGINS=/var/lib/grafana/plugins"
logger=settings t=2023-11-26T15:29:13.693517741Z level=info msg="Config overridden from Environment variable" var="GF_PATHS_PROVISIONING=/etc/grafana/provisioning"
logger=settings t=2023-11-26T15:29:13.693529814Z level=info msg="Config overridden from Environment variable" var="GF_USERS_ALLOW_SIGN_UP=false"
logger=settings t=2023-11-26T15:29:13.693542629Z level=info msg=Target target=[all]
logger=settings t=2023-11-26T15:29:13.693575183Z level=info msg="Path Home" path=/usr/share/grafana
logger=settings t=2023-11-26T15:29:13.693588256Z level=info msg="Path Data" path=/var/lib/grafana
logger=settings t=2023-11-26T15:29:13.693600515Z level=info msg="Path Logs" path=/var/log/grafana
logger=settings t=2023-11-26T15:29:13.693615144Z level=info msg="Path Plugins" path=/var/lib/grafana/plugins
logger=settings t=2023-11-26T15:29:13.693628273Z level=info msg="Path Provisioning" path=/etc/grafana/provisioning
logger=settings t=2023-11-26T15:29:13.693640828Z level=info msg="App mode production"
logger=sqlstore t=2023-11-26T15:29:13.694399941Z level=info msg="Connecting to DB" dbtype=sqlite3
logger=sqlstore t=2023-11-26T15:29:13.694454364Z level=warn msg="SQLite database file has broader permissions than it should" path=/var/lib/grafana/grafana.db mode=-rw-rw-r-- expected=-rw-r-----
logger=migrator t=2023-11-26T15:29:13.69606242Z level=info msg="Starting DB migrations"
Error: ✗ failed to check table existence: attempt to write a readonly database
GF_PATHS_DATA='/var/lib/grafana' is not writable.
You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migrate-to-v51-or-later
logger=settings t=2023-11-26T15:29:16.441772118Z level=info msg="Starting Grafana" version=10.2.2 commit=161e3cac5075540918e3a39004f2364ad104d5bb branch=HEAD compiled=2023-11-20T12:28:00Z
logger=settings t=2023-11-26T15:29:16.44265741Z level=info msg="Config loaded from" file=/usr/share/grafana/conf/defaults.ini
logger=settings t=2023-11-26T15:29:16.44279657Z level=info msg="Config loaded from" file=/etc/grafana/grafana.ini
logger=settings t=2023-11-26T15:29:16.44287927Z level=info msg="Config overridden from command line" arg="default.paths.data=/var/lib/grafana"
logger=settings t=2023-11-26T15:29:16.442952767Z level=info msg="Config overridden from command line" arg="default.paths.logs=/var/log/grafana"
logger=settings t=2023-11-26T15:29:16.443009505Z level=info msg="Config overridden from command line" arg="default.paths.plugins=/var/lib/grafana/plugins"
logger=settings t=2023-11-26T15:29:16.443098038Z level=info msg="Config overridden from command line" arg="default.paths.provisioning=/etc/grafana/provisioning"
logger=settings t=2023-11-26T15:29:16.443177997Z level=info msg="Config overridden from command line" arg="default.log.mode=console"
logger=settings t=2023-11-26T15:29:16.443253031Z level=info msg="Config overridden from Environment variable" var="GF_PATHS_DATA=/var/lib/grafana"
logger=settings t=2023-11-26T15:29:16.443329879Z level=info msg="Config overridden from Environment variable" var="GF_PATHS_LOGS=/var/log/grafana"
logger=settings t=2023-11-26T15:29:16.443423912Z level=info msg="Config overridden from Environment variable" var="GF_PATHS_PLUGINS=/var/lib/grafana/plugins"
logger=settings t=2023-11-26T15:29:16.443504982Z level=info msg="Config overridden from Environment variable" var="GF_PATHS_PROVISIONING=/etc/grafana/provisioning"
logger=settings t=2023-11-26T15:29:16.443576923Z level=info msg="Config overridden from Environment variable" var="GF_USERS_ALLOW_SIGN_UP=false"
logger=settings t=2023-11-26T15:29:16.443655031Z level=info msg=Target target=[all]
logger=settings t=2023-11-26T15:29:16.443745064Z level=info msg="Path Home" path=/usr/share/grafana
logger=settings t=2023-11-26T15:29:16.443802098Z level=info msg="Path Data" path=/var/lib/grafana
logger=settings t=2023-11-26T15:29:16.44389226Z level=info msg="Path Logs" path=/var/log/grafana
logger=settings t=2023-11-26T15:29:16.443948147Z level=info msg="Path Plugins" path=/var/lib/grafana/plugins
logger=settings t=2023-11-26T15:29:16.444035198Z level=info msg="Path Provisioning" path=/etc/grafana/provisioning
logger=settings t=2023-11-26T15:29:16.444091825Z level=info msg="App mode production"
logger=sqlstore t=2023-11-26T15:29:16.444945934Z level=info msg="Connecting to DB" dbtype=sqlite3
logger=sqlstore t=2023-11-26T15:29:16.445068391Z level=warn msg="SQLite database file has broader permissions than it should" path=/var/lib/grafana/grafana.db mode=-rw-rw-r-- expected=-rw-r-----
logger=migrator t=2023-11-26T15:29:16.446571507Z level=info msg="Starting DB migrations"
Error: ✗ failed to check table existence: attempt to write a readonly database
GF_PATHS_DATA='/var/lib/grafana' is not writable.
You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migrate-to-v51-or-later
logger=settings t=2023-11-26T15:29:20.837205834Z level=info msg="Starting Grafana" version=10.2.2 commit=161e3cac5075540918e3a39004f2364ad104d5bb branch=HEAD compiled=2023-11-20T12:28:00Z
logger=settings t=2023-11-26T15:29:20.838213584Z level=info msg="Config loaded from" file=/usr/share/grafana/conf/defaults.ini
logger=settings t=2023-11-26T15:29:20.838364725Z level=info msg="Config loaded from" file=/etc/grafana/grafana.ini
logger=settings t=2023-11-26T15:29:20.83844748Z level=info msg="Config overridden from command line" arg="default.paths.data=/var/lib/grafana"
logger=settings t=2023-11-26T15:29:20.838521588Z level=info msg="Config overridden from command line" arg="default.paths.logs=/var/log/grafana"
logger=settings t=2023-11-26T15:29:20.838577956Z level=info msg="Config overridden from command line" arg="default.paths.plugins=/var/lib/grafana/plugins"
logger=settings t=2023-11-26T15:29:20.838672729Z level=info msg="Config overridden from command line" arg="default.paths.provisioning=/etc/grafana/provisioning"
logger=settings t=2023-11-26T15:29:20.838749448Z level=info msg="Config overridden from command line" arg="default.log.mode=console"
logger=settings t=2023-11-26T15:29:20.838827129Z level=info msg="Config overridden from Environment variable" var="GF_PATHS_DATA=/var/lib/grafana"
logger=settings t=2023-11-26T15:29:20.838903255Z level=info msg="Config overridden from Environment variable" var="GF_PATHS_LOGS=/var/log/grafana"
logger=settings t=2023-11-26T15:29:20.838974474Z level=info msg="Config overridden from Environment variable" var="GF_PATHS_PLUGINS=/var/lib/grafana/plugins"
logger=settings t=2023-11-26T15:29:20.839031287Z level=info msg="Config overridden from Environment variable" var="GF_PATHS_PROVISIONING=/etc/grafana/provisioning"
logger=settings t=2023-11-26T15:29:20.839120079Z level=info msg="Config overridden from Environment variable" var="GF_USERS_ALLOW_SIGN_UP=false"
logger=settings t=2023-11-26T15:29:20.839178761Z level=info msg=Target target=[all]
logger=settings t=2023-11-26T15:29:20.83928896Z level=info msg="Path Home" path=/usr/share/grafana
logger=settings t=2023-11-26T15:29:20.839379956Z level=info msg="Path Data" path=/var/lib/grafana
logger=settings t=2023-11-26T15:29:20.839453749Z level=info msg="Path Logs" path=/var/log/grafana
logger=settings t=2023-11-26T15:29:20.83950969Z level=info msg="Path Plugins" path=/var/lib/grafana/plugins
logger=settings t=2023-11-26T15:29:20.839599094Z level=info msg="Path Provisioning" path=/etc/grafana/provisioning
logger=settings t=2023-11-26T15:29:20.839657498Z level=info msg="App mode production"
logger=sqlstore t=2023-11-26T15:29:20.840507015Z level=info msg="Connecting to DB" dbtype=sqlite3
logger=sqlstore t=2023-11-26T15:29:20.840635231Z level=warn msg="SQLite database file has broader permissions than it should" path=/var/lib/grafana/grafana.db mode=-rw-rw-r-- expected=-rw-r-----
logger=migrator t=2023-11-26T15:29:20.842177141Z level=info msg="Starting DB migrations"
Error: ✗ failed to check table existence: attempt to write a readonly database

**Comment by rmiddle** [comment]
The issue is likely related to you using an IP instead of a DNS name.  Please see this section of the install doc.
https://github.com/pi-hosted/pi-hosted/blob/master/docs/rpi_docker_monitor.md#setup-grafana
