### ISSUE TITLE
Deploying a container from portainer took forever

### ISSUE THREAD

**Issue by laleeroy** [novaspirit/pi-hosted#491]
**Context**
Fresh install of debian 64bit for PI4B. Installed docker and portainer using the scrip, when deploying a container using portainer, it wont finish.
I only installed 1 container successfully and it is adguard home.

Something like homarr, flaresolver can't be install

**Comment by rmiddle** [comment]
What error are you getting?  I need more information about your setup?

**Comment by laleeroy** [comment]
Nvm, seems like my sd card is dying
