### ISSUE TITLE
Recent updates to portainer update script broke portainer

### ISSUE THREAD

**Issue by dkarter** [novaspirit/pi-hosted#492]
A recent update appears to have changed the location that portainer uses to store data.

Users that ran the update script may find themselves with a fresh instance of portainer that does not contain any of their apps or settings.

For anyone encountering this, here is how I fixed it:

Something like 
```bash
# stop portainer
docker container ls | grep portainer | awk '{ print $1 }' | x^Cgs docker container stop

# move the new folder for portainer in case you ran it since the update
sudo mv /portainer/Files/AppData/Config/portainer/ /tmp/backup-new-portainer

# copy the files from the old volume to the new location
docker run --rm -v portainer_data:/portainer_data -v /portainer/Files/AppData/Config/portainer:/new_portainer busybox sh -c 'cp -r portainer_data/* /new_portainer/'

# start portainer again
docker start portainer
```

**Comment by rmiddle** [comment]
> A recent update appears to have changed the location that portainer uses to store data.
> 
> Users that ran the update script may find themselves with a fresh instance of portainer that does not contain any of their apps or settings.
> 
> For anyone encountering this, here is how I fixed it:
> 
> Something like
> 
> ```shell
> # stop portainer
> docker container ls | grep portainer | awk '{ print $1 }' | x^Cgs docker container stop
> 
> # move the new folder for portainer in case you ran it since the update
> sudo mv /portainer/Files/AppData/Config/portainer/ /tmp/backup-new-portainer
> 
> # copy the files from the old volume to the new location
> docker run --rm -v portainer_data:/portainer_data -v /portainer/Files/AppData/Config/portainer:/new_portainer busybox sh -c 'cp -r portainer_data/* /new_portainer/'
> 
> # start portainer again
> docker start portainer
> ```

Sorry about that but yes I updated the data folder so that Portainer data folder could be backed up and reinstalling.
