### ISSUE TITLE
Getting mounting issue in raspberry pi monitoring

### ISSUE THREAD

**Issue by shubhank-saxena** [novaspirit/pi-hosted#51]
Hi, I am getting the following error

```

Failure
OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/portainer/Files/AppData/Config/grafana/grafana.ini" to rootfs at "/etc/grafana/grafana.ini" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

```
All the containers have been spawned from stack, only `monitoring-grafana` is throwing this error. Please help :(

**Comment by Dschorim** [comment]
for some reason your grafana.ini is a directory; you can try to remove the grafana.ini, and then "touch /portainer/Files/AppData/Config/grafana/grafana.ini" and the nrecreating the container

**Comment by chadmark** [comment]
This was very helpful. Created the .ini file and the container is starting up for me. Still getting other weird errors in the Grafana log though. Looking through the YML file and the Grafana section. I can't see that any of these missing subdirectories are being created during the install or even when I run that initial shell script. Would love some feedback!


t=2021-10-12T20:24:34+0000 lvl=eror msg="can't read datasource provisioning files from directory" logger=provisioning.datasources path=/etc/grafana/provisioning/datasources error="open /etc/grafana/provisioning/datasources: no such file or directory"

t=2021-10-12T20:24:34+0000 lvl=eror msg="Failed to read plugin provisioning files from directory" logger=provisioning.plugins path=/etc/grafana/provisioning/plugins error="open /etc/grafana/provisioning/plugins: no such file or directory"

t=2021-10-12T20:24:34+0000 lvl=eror msg="Can't read alert notification provisioning files from directory" logger=provisioning.notifiers path=/etc/grafana/provisioning/notifiers error="open /etc/grafana/provisioning/notifiers: no such file or directory"

t=2021-10-12T20:24:34+0000 lvl=eror msg="can't read dashboard provisioning files from directory" logger=provisioning.dashboard path=/etc/grafana/provisioning/dashboards error="open /etc/grafana/provisioning/dashboards: no such file or directory"

**Comment by chadmark** [comment]
Solved it!

Got into /portainer/Files/AppData/Config/grafana/provisioning on the host and create the dashboards, plugins, notifiers and datasources sub directories. Restarted the container and no more errors AND it let me reset the password.
