### ISSUE TITLE
Can't access the AppTemplate - Portainer 2.9.1

### ISSUE THREAD

**Issue by Tchiimy** [novaspirit/pi-hosted#74]
Hi,

I recently can't access to the app template from : https://raw.githubusercontent.com/novaspirit/pi-hosted/master/pi-hosted_template/template/portainer-v2.json

In settings I get this error : 

![image](https://user-images.githubusercontent.com/75799578/138107720-e329e343-0c77-4172-85e0-04ba6d2b1200.png)

I don't really understand what is this "Helm Repository" but when I try to access the app template i have this error : 

![image](https://user-images.githubusercontent.com/75799578/138108013-6b1f0a94-4521-4281-b47c-0c4426657c4c.png)

Is it linked with this ?

**Comment by kylesmart2** [comment]
I had the same issue and a quick reboot fixed the error for me.
