### ISSUE TITLE
[REQUEST] feature request to update the templates so that the ports do not cause conflicts at all.

### ISSUE THREAD

**Issue by taroittech** [novaspirit/pi-hosted#80]
It would be great to have a portainer template where all the containers are configured so that the ports do not cause conflicts.

Also, it would be great to have a template that installs the entire stack of containers that are available from the portainer template.

**Comment by rmiddle** [comment]
tuta23 create some issue with duplicate ports to be adjusted based on scripts to pull port information from the scripts.  I am going to close this issue.
